/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.view;

import br.edu.uesb.petshop.control.TelaAddFuncionarioControl;
import br.edu.uesb.petshop.enumerado.EnumView;
import br.edu.uesb.petshop.model.Funcionario;
import br.edu.uesb.petshop.model.PetShop;
import br.edu.uesb.petshop.model.ValidarCpf;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus
 */
public class TelaAddFuncionario1 extends javax.swing.JPanel {

    private Campovazio cp = new Campovazio();
    private Funcionario funcionario;
    private TelaAddFuncionarioControl funcionarioControl;

    public TelaAddFuncionario1() {

        initComponents();
        funcionarioControl = new TelaAddFuncionarioControl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloAddFuncionario = new javax.swing.JLabel();
        txtNomeAddFuncionario = new javax.swing.JTextField();
        lbNomeAddFuncionario = new javax.swing.JLabel();
        txtEnderecoAddFuncionario = new javax.swing.JTextField();
        lbEnderecoAddFuncionario = new javax.swing.JLabel();
        lbBairroAddFuncionario = new javax.swing.JLabel();
        txtBairroAddFuncionario = new javax.swing.JTextField();
        lbComplementoAddFuncionario = new javax.swing.JLabel();
        txtComplementoAddFuncionario = new javax.swing.JTextField();
        lbSexoAddFuncionario = new javax.swing.JLabel();
        cbSexoAddFuncionario = new javax.swing.JComboBox();
        lbcpfAddFuncionario = new javax.swing.JLabel();
        txtCpfAddFuncionario = new javax.swing.JFormattedTextField();
        lbDataNascAddFuncionario = new javax.swing.JLabel();
        txtDataNascAddFuncionario = new javax.swing.JFormattedTextField();
        lbTelefone1AddFuncionario = new javax.swing.JLabel();
        txtTelefone1AddFuncionario = new javax.swing.JFormattedTextField();
        lbTelefone2AddFuncionario = new javax.swing.JLabel();
        txtTelefone2AddFuncionario = new javax.swing.JFormattedTextField();
        bLimparAddFuncionario = new javax.swing.JButton();
        bSalvarCadastroAddFuncionario = new javax.swing.JButton();
        bVoltarAddFuncionario = new javax.swing.JButton();
        bAtualizar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        lbTituloAddFuncionario.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloAddFuncionario.setText("ADICIONAR FUNCIONÁRIO");

        cp.capslock(txtNomeAddFuncionario);
        txtNomeAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAddFuncionarioActionPerformed(evt);
            }
        });

        lbNomeAddFuncionario.setText("Nome:");

        cp.capslock(txtEnderecoAddFuncionario);
        txtEnderecoAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoAddFuncionarioActionPerformed(evt);
            }
        });

        lbEnderecoAddFuncionario.setText("Endereço:");

        lbBairroAddFuncionario.setText("Bairro:");

        cp.capslock(txtBairroAddFuncionario);
        txtBairroAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroAddFuncionarioActionPerformed(evt);
            }
        });

        lbComplementoAddFuncionario.setText("Complemento:");

        cp.capslock(txtComplementoAddFuncionario);
        txtComplementoAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoAddFuncionarioActionPerformed(evt);
            }
        });

        lbSexoAddFuncionario.setText("Sexo:");

        cbSexoAddFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbSexoAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoAddFuncionarioActionPerformed(evt);
            }
        });

        lbcpfAddFuncionario.setText("CPF:");

        try {
            txtCpfAddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfAddFuncionarioActionPerformed(evt);
            }
        });

        lbDataNascAddFuncionario.setText("Data Nascimento:");

        try {
            txtDataNascAddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascAddFuncionarioActionPerformed(evt);
            }
        });

        lbTelefone1AddFuncionario.setText("Telefone 1:");

        try {
            txtTelefone1AddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone1AddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone1AddFuncionarioActionPerformed(evt);
            }
        });

        lbTelefone2AddFuncionario.setText("Telefone 2:");

        try {
            txtTelefone2AddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone2AddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone2AddFuncionarioActionPerformed(evt);
            }
        });

        bLimparAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/51.png"))); // NOI18N
        bLimparAddFuncionario.setText("LIMPAR");
        bLimparAddFuncionario.setPreferredSize(new java.awt.Dimension(67, 27));
        bLimparAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparAddFuncionarioActionPerformed(evt);
            }
        });

        bSalvarCadastroAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/4.png"))); // NOI18N
        bSalvarCadastroAddFuncionario.setText("SALVAR CADASTRO");
        bSalvarCadastroAddFuncionario.setPreferredSize(new java.awt.Dimension(4075, 27));
        bSalvarCadastroAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarCadastroAddFuncionarioActionPerformed(evt);
            }
        });

        bVoltarAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/15.png"))); // NOI18N
        bVoltarAddFuncionario.setText("VOLTAR");
        bVoltarAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarAddFuncionarioActionPerformed(evt);
            }
        });

        bAtualizar.setEnabled(false);
        bAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/39.png"))); // NOI18N
        bAtualizar.setText("ATUALIZAR");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        bExcluir.setEnabled(false);
        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/51.png"))); // NOI18N
        bExcluir.setText("EXCLUIR");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAddFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEnderecoAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbComplementoAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSexoAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTelefone1AddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtEnderecoAddFuncionario)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLimparAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVoltarAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(bSalvarCadastroAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSexoAddFuncionario, 0, 117, Short.MAX_VALUE)
                            .addComponent(txtTelefone1AddFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDataNascAddFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataNascAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTelefone2AddFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone2AddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtComplementoAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbBairroAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBairroAddFuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbcpfAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpfAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTituloAddFuncionario)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeAddFuncionario)
                    .addComponent(lbcpfAddFuncionario)
                    .addComponent(txtCpfAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnderecoAddFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplementoAddFuncionario)
                    .addComponent(txtComplementoAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBairroAddFuncionario)
                    .addComponent(txtBairroAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascAddFuncionario)
                    .addComponent(txtDataNascAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexoAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexoAddFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone1AddFuncionario)
                    .addComponent(txtTelefone1AddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefone2AddFuncionario)
                    .addComponent(txtTelefone2AddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLimparAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bVoltarAddFuncionario))
                    .addComponent(bSalvarCadastroAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbSexoAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoAddFuncionarioActionPerformed

    }//GEN-LAST:event_cbSexoAddFuncionarioActionPerformed

    private void bLimparAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparAddFuncionarioActionPerformed

        txtNomeAddFuncionario.setText("");
        txtEnderecoAddFuncionario.setText("");
        txtComplementoAddFuncionario.setText("");
        txtBairroAddFuncionario.setText("");
        txtCpfAddFuncionario.setText("");
        txtDataNascAddFuncionario.setText("");
        txtTelefone1AddFuncionario.setText("");
        txtTelefone2AddFuncionario.setText("");
        cbSexoAddFuncionario.setSelectedItem(0);
        cp.limparTextfield(txtNomeAddFuncionario);
        cp.limparTextfield(txtEnderecoAddFuncionario);
        cp.limparTextfield(txtBairroAddFuncionario);
        cp.limparFormattedtextfield(txtCpfAddFuncionario);
        cp.limparFormattedtextfield(txtDataNascAddFuncionario);
        cp.limparFormattedtextfield(txtTelefone1AddFuncionario);
        cp.limparCombobox(cbSexoAddFuncionario);

    }//GEN-LAST:event_bLimparAddFuncionarioActionPerformed

    private void bSalvarCadastroAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarCadastroAddFuncionarioActionPerformed

        String login = TelaAddFuncionario.login;
        String senha = TelaAddFuncionario.senha;
        cp.textfield(txtNomeAddFuncionario);
        cp.textfield(txtEnderecoAddFuncionario);
        cp.textfield(txtBairroAddFuncionario);
        cp.formattedtextfield(txtCpfAddFuncionario);
        cp.formattedtextfield(txtDataNascAddFuncionario);
        cp.formattedtextfield(txtTelefone1AddFuncionario);
        cp.combobox(cbSexoAddFuncionario);
        String cpf = txtCpfAddFuncionario.getText().substring(0, 3) + txtCpfAddFuncionario.getText().substring(4, 7) + txtCpfAddFuncionario.getText().substring(8, 11) + txtCpfAddFuncionario.getText().substring(12, 14);

        Date dataNasc = null;

        if (txtDataNascAddFuncionario.getText().equals("  /  /    ")) {
            dataNasc = null;
        } else {

            int ano = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(8, 10));
            int dia = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(0, 2));
            int mes = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(3, 5)) - 1;
            if (dia > 31 || mes > 11 || ano > 2100) {

                JOptionPane.showMessageDialog(this, "Entre com um data válida!", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else {
                if (Integer.parseInt(txtDataNascAddFuncionario.getText().substring(7, 10)) <= 100) {

                    ano = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(7, 10)) + 100;
                } else {
                    ano = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(8, 10));
                }

                dataNasc = new Date(ano, mes, dia);

            }
        }

        funcionario = new Funcionario(login, senha, txtNomeAddFuncionario.getText(), txtEnderecoAddFuncionario.getText(),
                txtBairroAddFuncionario.getText(), txtComplementoAddFuncionario.getText(),
                txtTelefone2AddFuncionario.getText(), txtCpfAddFuncionario.getText(),
                txtTelefone1AddFuncionario.getText(), dataNasc, cbSexoAddFuncionario.getSelectedItem().toString());

        if ((funcionario.getDataNasc() == null) || ("(  )     -    ".equals(funcionario.getTelefone1()))
                || ("".equals(funcionario.getNome())) || ("".equals(funcionario.getEndereco()))
                || ("".equals(funcionario.getBairro()))
                || ("   .   .   -  ".equals(funcionario.getCpf())) || ("Selecione...".equals(funcionario.getSexo()))) {

            JOptionPane.showMessageDialog(null, "Por favor preencha os campos restantes!", "Atenção", JOptionPane.WARNING_MESSAGE);

        } else {

            if (!ValidarCpf.isCPF(cpf)) {

                JOptionPane.showMessageDialog(this, "Entre com um CPF válido!", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else if (funcionarioControl.verificaCpfExistente(ValidarCpf.imprimeCPF(cpf))) {

                JOptionPane.showMessageDialog(this, "CPF já cadastrado!", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else {

                funcionarioControl.salvarFuncionario(funcionario);
                bLimparAddFuncionarioActionPerformed(evt);
                PetShop.tela.showView(EnumView.TELAFUNCIONARIO);

            }
        }


    }//GEN-LAST:event_bSalvarCadastroAddFuncionarioActionPerformed

    private void bVoltarAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarAddFuncionarioActionPerformed

        PetShop.tela.showView(EnumView.TELAADDFUNCIONARIO);
        bLimparAddFuncionarioActionPerformed(evt);

    }//GEN-LAST:event_bVoltarAddFuncionarioActionPerformed

    private void txtNomeAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAddFuncionarioActionPerformed

        txtCpfAddFuncionario.requestFocus();

    }//GEN-LAST:event_txtNomeAddFuncionarioActionPerformed

    private void txtCpfAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfAddFuncionarioActionPerformed

        txtEnderecoAddFuncionario.requestFocus();
    }//GEN-LAST:event_txtCpfAddFuncionarioActionPerformed

    private void txtEnderecoAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoAddFuncionarioActionPerformed

        txtComplementoAddFuncionario.requestFocus();

    }//GEN-LAST:event_txtEnderecoAddFuncionarioActionPerformed

    private void txtComplementoAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoAddFuncionarioActionPerformed

        txtBairroAddFuncionario.requestFocus();

    }//GEN-LAST:event_txtComplementoAddFuncionarioActionPerformed

    private void txtBairroAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroAddFuncionarioActionPerformed

        cbSexoAddFuncionario.requestFocus();

    }//GEN-LAST:event_txtBairroAddFuncionarioActionPerformed

    private void txtDataNascAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascAddFuncionarioActionPerformed

        txtTelefone1AddFuncionario.requestFocus();

    }//GEN-LAST:event_txtDataNascAddFuncionarioActionPerformed

    private void txtTelefone2AddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone2AddFuncionarioActionPerformed

        bSalvarCadastroAddFuncionarioActionPerformed(evt);

    }//GEN-LAST:event_txtTelefone2AddFuncionarioActionPerformed

    private void txtTelefone1AddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone1AddFuncionarioActionPerformed

        txtTelefone2AddFuncionario.requestFocus();

    }//GEN-LAST:event_txtTelefone1AddFuncionarioActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed

        ResultSet rs = funcionarioControl.buscarByCpf(txtCpfAddFuncionario.getText());
        funcionario = null;
        try {
            if (rs.next()) {
                funcionario = new Funcionario(rs.getInt("id"), rs.getString("login"),
                        rs.getString("senha"), rs.getString("nome"),
                        rs.getString("endereco"), rs.getString("bairro"),
                        rs.getString("complemento"), rs.getString("telefone2"),
                        rs.getString("cpf"), rs.getString("telefone1"),
                        rs.getDate("datanascimento"), rs.getString("sexo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAddFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

        funcionarioControl.excluirFuncionario(funcionario);
        bLimparAddFuncionarioActionPerformed(evt);
        PetShop.tela.showView(EnumView.TELAFUNCIONARIO);

    }//GEN-LAST:event_bExcluirActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed

        ResultSet rs = funcionarioControl.buscarByCpf(txtCpfAddFuncionario.getText());
        funcionario = null;
        try {
            if (rs.next()) {
                funcionario = new Funcionario(rs.getInt("id"), rs.getString("login"),
                        rs.getString("senha"), txtNomeAddFuncionario.getText(),
                        txtEnderecoAddFuncionario.getText(), txtBairroAddFuncionario.getText(),
                        txtComplementoAddFuncionario.getText(), txtTelefone2AddFuncionario.getText(),
                        txtCpfAddFuncionario.getText(), txtTelefone1AddFuncionario.getText(),
                        rs.getDate("datanascimento"), cbSexoAddFuncionario.getSelectedItem().toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAddFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

        funcionarioControl.atualizarFuncionario(funcionario);
        bLimparAddFuncionarioActionPerformed(evt);
        PetShop.tela.showView(EnumView.TELAFUNCIONARIO);

    }//GEN-LAST:event_bAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bLimparAddFuncionario;
    private javax.swing.JButton bSalvarCadastroAddFuncionario;
    private javax.swing.JButton bVoltarAddFuncionario;
    private javax.swing.JComboBox cbSexoAddFuncionario;
    private javax.swing.JLabel lbBairroAddFuncionario;
    private javax.swing.JLabel lbComplementoAddFuncionario;
    private javax.swing.JLabel lbDataNascAddFuncionario;
    private javax.swing.JLabel lbEnderecoAddFuncionario;
    private javax.swing.JLabel lbNomeAddFuncionario;
    private javax.swing.JLabel lbSexoAddFuncionario;
    private javax.swing.JLabel lbTelefone1AddFuncionario;
    private javax.swing.JLabel lbTelefone2AddFuncionario;
    private javax.swing.JLabel lbTituloAddFuncionario;
    private javax.swing.JLabel lbcpfAddFuncionario;
    private javax.swing.JTextField txtBairroAddFuncionario;
    private javax.swing.JTextField txtComplementoAddFuncionario;
    private javax.swing.JFormattedTextField txtCpfAddFuncionario;
    private javax.swing.JFormattedTextField txtDataNascAddFuncionario;
    private javax.swing.JTextField txtEnderecoAddFuncionario;
    private javax.swing.JTextField txtNomeAddFuncionario;
    private javax.swing.JFormattedTextField txtTelefone1AddFuncionario;
    private javax.swing.JFormattedTextField txtTelefone2AddFuncionario;
    // End of variables declaration//GEN-END:variables

    public void setTxtBairroAddFuncionario(String txtBairroAddFuncionario) {
        this.txtBairroAddFuncionario.setText(txtBairroAddFuncionario);
    }

    public void setTxtComplementoAddFuncionario(String txtComplementoAddFuncionario) {
        this.txtComplementoAddFuncionario.setText(txtComplementoAddFuncionario);
    }

    public void setTxtCpfAddFuncionario(String txtCpfAddFuncionario) {
        this.txtCpfAddFuncionario.setText(txtCpfAddFuncionario);
    }

    public void setNoEditCPf(boolean estado) {
        this.txtCpfAddFuncionario.setEditable(estado);
    }

    public void setTxtDataNascAddFuncionario(String txtDataNascAddFuncionario) {
        this.txtDataNascAddFuncionario.setText(txtDataNascAddFuncionario);
    }

    public void setTxtEnderecoAddFuncionario(String txtEnderecoAddFuncionario) {
        this.txtEnderecoAddFuncionario.setText(txtEnderecoAddFuncionario);
    }

    public void setTxtNomeAddFuncionario(String txtNomeAddFuncionario) {
        this.txtNomeAddFuncionario.setText(txtNomeAddFuncionario);
    }

    public void setTxtTelefone1AddFuncionario(String txtTelefone1AddFuncionario) {
        this.txtTelefone1AddFuncionario.setText(txtTelefone1AddFuncionario);
    }

    public void setTxtTelefone2AddFuncionario(String txtTelefone2AddFuncionario) {
        this.txtTelefone2AddFuncionario.setText(txtTelefone2AddFuncionario);
    }

    public void setCbSexoAddFuncionario(String cbSexoAddFuncionario) {
        this.cbSexoAddFuncionario.setSelectedItem(cbSexoAddFuncionario);
    }

    public void setbEnableExcluir(boolean estado) {
        this.bExcluir.setEnabled(estado);
    }

    public void setbEnableAtualizar(boolean estado) {
        this.bAtualizar.setEnabled(estado);
    }

    public void setbEnableSalvar(boolean estado) {
        this.bSalvarCadastroAddFuncionario.setEnabled(estado);
    }
}
