/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.view;

import br.edu.uesb.petshop.enumerado.EnumView;
import br.edu.uesb.petshop.model.PetShop;

/**
 *
 * @author matheus
 */
public class TelaAddFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaAddFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLoginTelaFunc = new javax.swing.JLabel();
        lbTituloTelaFunc = new javax.swing.JLabel();
        lbSenhaTelaFunc = new javax.swing.JLabel();
        lbConfirmaTelaFunc = new javax.swing.JLabel();
        bCancelarTelaFunc = new javax.swing.JButton();
        bSegunteTelaFunc = new javax.swing.JButton();
        txtLoginTelaFunc = new javax.swing.JTextField();
        txtSenhaTelaFunc = new javax.swing.JPasswordField();
        txtConfirmaTelaFunc = new javax.swing.JPasswordField();

        lbLoginTelaFunc.setText("Login:");

        lbTituloTelaFunc.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTituloTelaFunc.setText("ADICIONAR FUNCIONÁRIO");

        lbSenhaTelaFunc.setText("Senha:");

        lbConfirmaTelaFunc.setText("Confirmar Senha:");

        bCancelarTelaFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/15.png"))); // NOI18N
        bCancelarTelaFunc.setText("VOLTAR");
        bCancelarTelaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarTelaFuncActionPerformed(evt);
            }
        });

        bSegunteTelaFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/16.png"))); // NOI18N
        bSegunteTelaFunc.setText("PROXIMO");
        bSegunteTelaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSegunteTelaFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloTelaFunc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbConfirmaTelaFunc, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(lbSenhaTelaFunc)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(lbLoginTelaFunc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bCancelarTelaFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSegunteTelaFunc))
                            .addComponent(txtConfirmaTelaFunc)
                            .addComponent(txtSenhaTelaFunc)
                            .addComponent(txtLoginTelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTituloTelaFunc)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoginTelaFunc)
                    .addComponent(txtLoginTelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenhaTelaFunc)
                    .addComponent(txtSenhaTelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmaTelaFunc)
                    .addComponent(txtConfirmaTelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelarTelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSegunteTelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarTelaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarTelaFuncActionPerformed
        
        PetShop.tela.showView(EnumView.TELAFUNCIONARIO);
        
    }//GEN-LAST:event_bCancelarTelaFuncActionPerformed

    private void bSegunteTelaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSegunteTelaFuncActionPerformed
        
        PetShop.tela.showView(EnumView.TELAADDFUNCIONARIO2);
        
    }//GEN-LAST:event_bSegunteTelaFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarTelaFunc;
    private javax.swing.JButton bSegunteTelaFunc;
    private javax.swing.JLabel lbConfirmaTelaFunc;
    private javax.swing.JLabel lbLoginTelaFunc;
    private javax.swing.JLabel lbSenhaTelaFunc;
    private javax.swing.JLabel lbTituloTelaFunc;
    private javax.swing.JPasswordField txtConfirmaTelaFunc;
    private javax.swing.JTextField txtLoginTelaFunc;
    private javax.swing.JPasswordField txtSenhaTelaFunc;
    // End of variables declaration//GEN-END:variables
}
