/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.view;

import br.edu.uesb.petshop.control.TelaAddFuncionarioControl;
import br.edu.uesb.petshop.enumerado.EnumView;
import br.edu.uesb.petshop.model.Funcionario;
import br.edu.uesb.petshop.model.PetShop;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus
 */
public class TelaAddFuncionario1 extends javax.swing.JPanel {

    private Campovazio cp;
    private Funcionario funcionario;
    private TelaAddFuncionarioControl funcionarioControl = new TelaAddFuncionarioControl();
    

    public TelaAddFuncionario1() {
        initComponents();
        cp = new Campovazio();
//        cliente = new Cliente(null, null, null, null, null, null, null, null, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloAddFuncionario = new javax.swing.JLabel();
        txtNomeAddFuncionario = new javax.swing.JTextField();
        lbNomeAddFuncionario = new javax.swing.JLabel();
        txtEnderecoAddFuncionario = new javax.swing.JTextField();
        lbEnderecoAddFuncionario = new javax.swing.JLabel();
        lbBairroAddFuncionario = new javax.swing.JLabel();
        txtBairroAddFuncionario = new javax.swing.JTextField();
        lbComplementoAddFuncionario = new javax.swing.JLabel();
        txtComplementoAddFuncionario = new javax.swing.JTextField();
        lbSexoAddFuncionario = new javax.swing.JLabel();
        cbSexoAddFuncionario = new javax.swing.JComboBox();
        lbcpfAddFuncionario = new javax.swing.JLabel();
        txtCpfAddFuncionario = new javax.swing.JFormattedTextField();
        lbDataNascAddFuncionario = new javax.swing.JLabel();
        txtDataNascAddFuncionario = new javax.swing.JFormattedTextField();
        lbTelefone1AddFuncionario = new javax.swing.JLabel();
        txtTelefone1AddFuncionario = new javax.swing.JFormattedTextField();
        lbTelefone2AddFuncionario = new javax.swing.JLabel();
        txtTelefone2AddFuncionario = new javax.swing.JFormattedTextField();
        bLimparAddFuncionario = new javax.swing.JButton();
        bSalvarCadastroAddFuncionario = new javax.swing.JButton();
        bVoltarAddFuncionario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        lbTituloAddFuncionario.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloAddFuncionario.setText("ADICIONAR FUNCIONÁRIO");

        txtNomeAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAddFuncionarioActionPerformed(evt);
            }
        });

        lbNomeAddFuncionario.setText("Nome:");

        lbEnderecoAddFuncionario.setText("Endereço:");

        lbBairroAddFuncionario.setText("Bairro:");

        lbComplementoAddFuncionario.setText("Complemento:");

        lbSexoAddFuncionario.setText("Sexo:");

        cbSexoAddFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbSexoAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoAddFuncionarioActionPerformed(evt);
            }
        });

        lbcpfAddFuncionario.setText("CPF:");

        try {
            txtCpfAddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbDataNascAddFuncionario.setText("Data Nascimento:");

        try {
            txtDataNascAddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone1AddFuncionario.setText("Telefone 1:");

        try {
            txtTelefone1AddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone2AddFuncionario.setText("Telefone 2:");

        try {
            txtTelefone2AddFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bLimparAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/51.png"))); // NOI18N
        bLimparAddFuncionario.setText("LIMPAR");
        bLimparAddFuncionario.setPreferredSize(new java.awt.Dimension(67, 27));
        bLimparAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparAddFuncionarioActionPerformed(evt);
            }
        });

        bSalvarCadastroAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/4.png"))); // NOI18N
        bSalvarCadastroAddFuncionario.setText("SALVAR CADASTRO");
        bSalvarCadastroAddFuncionario.setPreferredSize(new java.awt.Dimension(4075, 27));
        bSalvarCadastroAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarCadastroAddFuncionarioActionPerformed(evt);
            }
        });

        bVoltarAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/15.png"))); // NOI18N
        bVoltarAddFuncionario.setText("VOLTAR");
        bVoltarAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarAddFuncionarioActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/39.png"))); // NOI18N
        jButton1.setText("EDITAR");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/51.png"))); // NOI18N
        jButton2.setText("EXCLUIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAddFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEnderecoAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbComplementoAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSexoAddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTelefone1AddFuncionario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtEnderecoAddFuncionario)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLimparAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVoltarAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(bSalvarCadastroAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSexoAddFuncionario, 0, 117, Short.MAX_VALUE)
                            .addComponent(txtTelefone1AddFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDataNascAddFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataNascAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTelefone2AddFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone2AddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtComplementoAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbBairroAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBairroAddFuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbcpfAddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpfAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTituloAddFuncionario)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeAddFuncionario)
                    .addComponent(lbcpfAddFuncionario)
                    .addComponent(txtCpfAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnderecoAddFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplementoAddFuncionario)
                    .addComponent(txtComplementoAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBairroAddFuncionario)
                    .addComponent(txtBairroAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascAddFuncionario)
                    .addComponent(txtDataNascAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexoAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexoAddFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone1AddFuncionario)
                    .addComponent(txtTelefone1AddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefone2AddFuncionario)
                    .addComponent(txtTelefone2AddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLimparAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bVoltarAddFuncionario))
                    .addComponent(bSalvarCadastroAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbSexoAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoAddFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoAddFuncionarioActionPerformed

    private void bLimparAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparAddFuncionarioActionPerformed

        txtNomeAddFuncionario.setText("");
        txtEnderecoAddFuncionario.setText("");
        txtComplementoAddFuncionario.setText("");
        txtBairroAddFuncionario.setText("");
        txtCpfAddFuncionario.setText("");
        txtDataNascAddFuncionario.setText("");
        txtTelefone1AddFuncionario.setText("");
        txtTelefone2AddFuncionario.setText("");
        cbSexoAddFuncionario.setSelectedItem(0);
        cp.limparTextfield(txtNomeAddFuncionario);
        cp.limparTextfield(txtEnderecoAddFuncionario);
        cp.limparTextfield(txtBairroAddFuncionario);
        cp.limparFormattedtextfield(txtCpfAddFuncionario);
        cp.limparFormattedtextfield(txtDataNascAddFuncionario);
        cp.limparFormattedtextfield(txtTelefone1AddFuncionario);
        cp.limparCombobox(cbSexoAddFuncionario);

    }//GEN-LAST:event_bLimparAddFuncionarioActionPerformed

    private void bSalvarCadastroAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarCadastroAddFuncionarioActionPerformed

        String login = TelaAddFuncionario.login;
        String senha = TelaAddFuncionario.senha;
//        String login = Fun.getTxtLoginTelaFunc();
//        String senha = func.getTxtSenhaTelaFunc();
        cp.textfield(txtNomeAddFuncionario);
        cp.textfield(txtEnderecoAddFuncionario);
        cp.textfield(txtBairroAddFuncionario);
        cp.formattedtextfield(txtCpfAddFuncionario);
        cp.formattedtextfield(txtDataNascAddFuncionario);
        cp.formattedtextfield(txtTelefone1AddFuncionario);
        cp.combobox(cbSexoAddFuncionario);
        Date dataNasc;

        if (txtDataNascAddFuncionario.getText().equals("  /  /    ")) {
            dataNasc = null;
        } else {

            int ano = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(8, 10));
            int dia = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(0, 2));
            int mes = Integer.parseInt(txtDataNascAddFuncionario.getText().substring(3, 5)) - 1;
            dataNasc = new Date(ano, mes, dia);
        }
        funcionario = new Funcionario(login, senha, txtNomeAddFuncionario.getText(), txtEnderecoAddFuncionario.getText(),
                txtBairroAddFuncionario.getText(), txtComplementoAddFuncionario.getText(),
                txtTelefone2AddFuncionario.getText(), txtCpfAddFuncionario.getText(),
                txtTelefone1AddFuncionario.getText(), dataNasc, cbSexoAddFuncionario.getSelectedItem().toString());

        if ((funcionario.getDataNasc() == null) || ("(  )     -    ".equals(funcionario.getTelefone1()))
                || ("".equals(funcionario.getNome())) || ("".equals(funcionario.getEndereco()))
                || ("".equals(funcionario.getBairro()))
                || ("   .   .   -  ".equals(funcionario.getCpf())) || ("Selecione...".equals(funcionario.getSexo()))) {

            JOptionPane.showMessageDialog(null, "Por favor preencha os campos restantes!", "Atenção", JOptionPane.WARNING_MESSAGE);

        } else {
            funcionarioControl.salvarFuncionario(funcionario);
        }


    }//GEN-LAST:event_bSalvarCadastroAddFuncionarioActionPerformed

    private void bVoltarAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarAddFuncionarioActionPerformed

        PetShop.tela.showView(EnumView.TELAADDFUNCIONARIO);
        bLimparAddFuncionarioActionPerformed(evt);

    }//GEN-LAST:event_bVoltarAddFuncionarioActionPerformed

    private void txtNomeAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAddFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAddFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLimparAddFuncionario;
    private javax.swing.JButton bSalvarCadastroAddFuncionario;
    private javax.swing.JButton bVoltarAddFuncionario;
    private javax.swing.JComboBox cbSexoAddFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbBairroAddFuncionario;
    private javax.swing.JLabel lbComplementoAddFuncionario;
    private javax.swing.JLabel lbDataNascAddFuncionario;
    private javax.swing.JLabel lbEnderecoAddFuncionario;
    private javax.swing.JLabel lbNomeAddFuncionario;
    private javax.swing.JLabel lbSexoAddFuncionario;
    private javax.swing.JLabel lbTelefone1AddFuncionario;
    private javax.swing.JLabel lbTelefone2AddFuncionario;
    private javax.swing.JLabel lbTituloAddFuncionario;
    private javax.swing.JLabel lbcpfAddFuncionario;
    private javax.swing.JTextField txtBairroAddFuncionario;
    private javax.swing.JTextField txtComplementoAddFuncionario;
    private javax.swing.JFormattedTextField txtCpfAddFuncionario;
    private javax.swing.JFormattedTextField txtDataNascAddFuncionario;
    private javax.swing.JTextField txtEnderecoAddFuncionario;
    private javax.swing.JTextField txtNomeAddFuncionario;
    private javax.swing.JFormattedTextField txtTelefone1AddFuncionario;
    private javax.swing.JFormattedTextField txtTelefone2AddFuncionario;
    // End of variables declaration//GEN-END:variables
}
