/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.view;

import br.edu.uesb.petshop.model.PetShop;
import java.util.ArrayList;
import javax.swing.JCheckBox;

/**
 *
 * @author matheus
 */
public class TelaAddExame extends javax.swing.JFrame {

    /**
     * Creates new form TelaAddExame
     */
    ArrayList<JCheckBox> checkboxes;

    JCheckBox exame;
    private TelaAdicionarNaListaExame telaaddnalista = null;
    
    public TelaAddExame() {
        initComponents();
        checkboxes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pExame = new javax.swing.JPanel();
        jLabelExames = new javax.swing.JLabel();
        jButtonOkExames = new javax.swing.JButton();
        jButtonCancelarExames = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        bAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelExames.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelExames.setText("EXAMES");

        jButtonOkExames.setText("OK");
        jButtonOkExames.setPreferredSize(new java.awt.Dimension(96, 51));
        jButtonOkExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkExamesActionPerformed(evt);
            }
        });

        jButtonCancelarExames.setText("CANCELAR");
        jButtonCancelarExames.setPreferredSize(new java.awt.Dimension(96, 51));
        jButtonCancelarExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarExamesActionPerformed(evt);
            }
        });

        bRemover.setText("REMOVER");

        bAdicionar.setText("ADICIONAR");
        bAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(14, 150));
        jPanel1.setLayout(new javax.swing.BoxLayout(pExame, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout pExameLayout = new javax.swing.GroupLayout(pExame);
        pExame.setLayout(pExameLayout);
        pExameLayout.setHorizontalGroup(
            pExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pExameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabelExames, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(bRemover, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, pExameLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButtonCancelarExames, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOkExames, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(bAdicionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pExameLayout.setVerticalGroup(
            pExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pExameLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabelExames, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOkExames, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarExames, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkExamesActionPerformed

    }//GEN-LAST:event_jButtonOkExamesActionPerformed

    private void jButtonCancelarExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarExamesActionPerformed
        PetShop.tela.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarExamesActionPerformed

    private void bAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarActionPerformed
      telaaddnalista = new TelaAdicionarNaListaExame();
        telaaddnalista.setVisible(true);
        PetShop.tela.setEnabled(false);
        
        //teste
//        teste.tela.setEnabled(false);
    }//GEN-LAST:event_bAdicionarActionPerformed

    private void adicionarListaExames() {
        exame = new JCheckBox();
        exame.setText("teste");
        jPanel1.add(exame);
        checkboxes.add(exame);
        jPanel1.updateUI();

//        for (int i=0; i <= checkboxes.size();i++){
        for (JCheckBox cbx : checkboxes) {
            System.out.println(cbx.getText());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionar;
    private javax.swing.JButton bRemover;
    private javax.swing.JButton jButtonCancelarExames;
    private javax.swing.JButton jButtonOkExames;
    private javax.swing.JLabel jLabelExames;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pExame;
    // End of variables declaration//GEN-END:variables
}
