/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.view;

import br.edu.uesb.petshop.control.TelaAddClienteControl;
import br.edu.uesb.petshop.enumerado.EnumView;
import br.edu.uesb.petshop.model.Cliente;
import br.edu.uesb.petshop.model.PetShop;
import br.edu.uesb.petshop.model.ValidarCpf;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus
 */
public class TelaAddCliente extends javax.swing.JPanel {

    private Campovazio cp;
    private Cliente cliente;
    private TelaAddClienteControl clienteControl = new TelaAddClienteControl();

    public TelaAddCliente() {
        initComponents();
        cp = new Campovazio();
//        cliente = new Cliente(null, null, null, null, null, null, null, null, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloAddCliente = new javax.swing.JLabel();
        txtNomeAddCliente = new javax.swing.JTextField();
        lbNomeAddCdiente = new javax.swing.JLabel();
        txtEnderecoAddCliente = new javax.swing.JTextField();
        lbEnderecoAddCliente = new javax.swing.JLabel();
        lbBairroAddCliente = new javax.swing.JLabel();
        txtBairroAddCliente = new javax.swing.JTextField();
        lbComplementoAddCliente = new javax.swing.JLabel();
        txtComplementoAddCliente = new javax.swing.JTextField();
        lbSexoAddCliente = new javax.swing.JLabel();
        cbSexoAddCliente = new javax.swing.JComboBox();
        lbcpfAddCliente = new javax.swing.JLabel();
        txtCpfAddCliente = new javax.swing.JFormattedTextField();
        lbDataNascAddCliente = new javax.swing.JLabel();
        txtDataNascAddCliente = new javax.swing.JFormattedTextField();
        lbTelefone1AddCliente = new javax.swing.JLabel();
        txtTelefone1AddCliente = new javax.swing.JFormattedTextField();
        lbTelefone2AddCliente = new javax.swing.JLabel();
        txtTelefone2AddCliente = new javax.swing.JFormattedTextField();
        bLimparAddCliente = new javax.swing.JButton();
        bSalvarCadastroAddCliente = new javax.swing.JButton();
        bVoltarAddCliente = new javax.swing.JButton();
        bAtualizar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        lbTituloAddCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloAddCliente.setText("ADICIONAR CLIENTE");

        txtNomeAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAddClienteActionPerformed(evt);
            }
        });

        lbNomeAddCdiente.setText("Nome:");

        txtEnderecoAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoAddClienteActionPerformed(evt);
            }
        });

        lbEnderecoAddCliente.setText("Endereço:");

        lbBairroAddCliente.setText("Bairro:");

        txtBairroAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroAddClienteActionPerformed(evt);
            }
        });

        lbComplementoAddCliente.setText("Complemento:");

        txtComplementoAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoAddClienteActionPerformed(evt);
            }
        });

        lbSexoAddCliente.setText("Sexo:");

        cbSexoAddCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbSexoAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoAddClienteActionPerformed(evt);
            }
        });

        lbcpfAddCliente.setText("CPF:");

        try {
            txtCpfAddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfAddClienteActionPerformed(evt);
            }
        });

        lbDataNascAddCliente.setText("Data Nascimento:");

        try {
            txtDataNascAddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascAddClienteActionPerformed(evt);
            }
        });

        lbTelefone1AddCliente.setText("Telefone 1:");

        try {
            txtTelefone1AddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone1AddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone1AddClienteActionPerformed(evt);
            }
        });

        lbTelefone2AddCliente.setText("Telefone 2:");

        try {
            txtTelefone2AddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone2AddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone2AddClienteActionPerformed(evt);
            }
        });

        bLimparAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/51.png"))); // NOI18N
        bLimparAddCliente.setText("LIMPAR");
        bLimparAddCliente.setPreferredSize(new java.awt.Dimension(67, 27));
        bLimparAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparAddClienteActionPerformed(evt);
            }
        });

        bSalvarCadastroAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/4.png"))); // NOI18N
        bSalvarCadastroAddCliente.setText("SALVAR CADASTRO");
        bSalvarCadastroAddCliente.setPreferredSize(new java.awt.Dimension(4075, 27));
        bSalvarCadastroAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarCadastroAddClienteActionPerformed(evt);
            }
        });

        bVoltarAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/15.png"))); // NOI18N
        bVoltarAddCliente.setText("VOLTAR");
        bVoltarAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarAddClienteActionPerformed(evt);
            }
        });

        bAtualizar.setEnabled(false);
        bAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/39.png"))); // NOI18N
        bAtualizar.setText("ATUALIZAR");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        bExcluir.setEnabled(false);
        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/51.png"))); // NOI18N
        bExcluir.setText("EXCLUIR");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAddCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeAddCdiente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEnderecoAddCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbComplementoAddCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSexoAddCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTelefone1AddCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtEnderecoAddCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLimparAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVoltarAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(bSalvarCadastroAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSexoAddCliente, 0, 117, Short.MAX_VALUE)
                            .addComponent(txtTelefone1AddCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDataNascAddCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataNascAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTelefone2AddCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone2AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtComplementoAddCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbBairroAddCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBairroAddCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeAddCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbcpfAddCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpfAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTituloAddCliente)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeAddCdiente)
                    .addComponent(lbcpfAddCliente)
                    .addComponent(txtCpfAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnderecoAddCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplementoAddCliente)
                    .addComponent(txtComplementoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBairroAddCliente)
                    .addComponent(txtBairroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascAddCliente)
                    .addComponent(txtDataNascAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexoAddCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone1AddCliente)
                    .addComponent(txtTelefone1AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefone2AddCliente)
                    .addComponent(txtTelefone2AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLimparAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bVoltarAddCliente))
                    .addComponent(bSalvarCadastroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbSexoAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoAddClienteActionPerformed

    }//GEN-LAST:event_cbSexoAddClienteActionPerformed

    private void bLimparAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparAddClienteActionPerformed

        txtNomeAddCliente.setText("");
        txtEnderecoAddCliente.setText("");
        txtComplementoAddCliente.setText("");
        txtBairroAddCliente.setText("");
        txtCpfAddCliente.setText("");
        txtDataNascAddCliente.setText("");
        txtTelefone1AddCliente.setText("");
        txtTelefone2AddCliente.setText("");
        cbSexoAddCliente.setSelectedItem("Selecione...");
        cp.limparTextfield(txtNomeAddCliente);
        cp.limparTextfield(txtEnderecoAddCliente);
        cp.limparTextfield(txtBairroAddCliente);
        cp.limparFormattedtextfield(txtCpfAddCliente);
        cp.limparFormattedtextfield(txtDataNascAddCliente);
        cp.limparFormattedtextfield(txtTelefone1AddCliente);
        cp.limparCombobox(cbSexoAddCliente);

    }//GEN-LAST:event_bLimparAddClienteActionPerformed

    private void bSalvarCadastroAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarCadastroAddClienteActionPerformed
        cp.textfield(txtNomeAddCliente);
        cp.textfield(txtEnderecoAddCliente);
        cp.textfield(txtBairroAddCliente);
        cp.formattedtextfield(txtCpfAddCliente);
        cp.formattedtextfield(txtDataNascAddCliente);
        cp.formattedtextfield(txtTelefone1AddCliente);
        cp.combobox(cbSexoAddCliente);
        String cpf = txtCpfAddCliente.getText().substring(0, 3) + txtCpfAddCliente.getText().substring(4, 7) + txtCpfAddCliente.getText().substring(8, 11) + txtCpfAddCliente.getText().substring(12, 14);

        Date dataNasc = null;

        if (txtDataNascAddCliente.getText().equals("  /  /    ")) {
            dataNasc = null;
        } else {

            int dia = Integer.parseInt(txtDataNascAddCliente.getText().substring(0, 2));
            int mes = Integer.parseInt(txtDataNascAddCliente.getText().substring(3, 5)) - 1;
            int ano = Integer.parseInt(txtDataNascAddCliente.getText().substring(6, 10));

            if (dia > 31 || mes > 11 || ano > 2100) {

                JOptionPane.showMessageDialog(this, "Entre com um data válida!", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else {

                if (Integer.parseInt(txtDataNascAddCliente.getText().substring(7, 10)) <= 100) {

                    ano = Integer.parseInt(txtDataNascAddCliente.getText().substring(7, 10)) + 100;
                } else {
                    ano = Integer.parseInt(txtDataNascAddCliente.getText().substring(8, 10));
                }

                dataNasc = new Date(ano, mes, dia);

            }
        }

        cliente = new Cliente(txtNomeAddCliente.getText(), txtEnderecoAddCliente.getText(),
                txtBairroAddCliente.getText(), txtComplementoAddCliente.getText(),
                txtTelefone2AddCliente.getText(), txtCpfAddCliente.getText(),
                txtTelefone1AddCliente.getText(), dataNasc, cbSexoAddCliente.getSelectedItem().toString());

        if ((cliente.getDataNasc() == null) || ("(  )     -    ".equals(cliente.getTelefone1()))
                || ("".equals(cliente.getNome())) || ("".equals(cliente.getEndereco()))
                || ("".equals(cliente.getBairro()))
                || ("   .   .   -  ".equals(cliente.getCpf())) || ("Selecione...".equals(cliente.getSexo()))) {

            JOptionPane.showMessageDialog(null, "Por favor preencha os campos restantes!", "Atenção", JOptionPane.WARNING_MESSAGE);

        } else {
            if (!ValidarCpf.isCPF(cpf)) {

                JOptionPane.showMessageDialog(this, "Entre com um CPF válido!", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else if (clienteControl.verificaCpfExistente(ValidarCpf.imprimeCPF(cpf))) {

                JOptionPane.showMessageDialog(this, "CPF já cadastrado!", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else {

                clienteControl.salvarCliente(cliente);
                bLimparAddClienteActionPerformed(evt);

            }

        }


    }//GEN-LAST:event_bSalvarCadastroAddClienteActionPerformed

    private void bVoltarAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarAddClienteActionPerformed

        PetShop.tela.showView(EnumView.TELACLIENTE);
        bLimparAddClienteActionPerformed(evt);

    }//GEN-LAST:event_bVoltarAddClienteActionPerformed

    private void txtNomeAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAddClienteActionPerformed
<<<<<<< HEAD
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAddClienteActionPerformed

=======

        cp.capslock(txtNomeAddCliente);
        txtCpfAddCliente.requestFocus();

    }//GEN-LAST:event_txtNomeAddClienteActionPerformed

    private void txtCpfAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfAddClienteActionPerformed

        txtEnderecoAddCliente.requestFocus();

    }//GEN-LAST:event_txtCpfAddClienteActionPerformed

    private void txtEnderecoAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoAddClienteActionPerformed

        cp.capslock(txtEnderecoAddCliente);
        txtComplementoAddCliente.requestFocus();

    }//GEN-LAST:event_txtEnderecoAddClienteActionPerformed

    private void txtComplementoAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoAddClienteActionPerformed

        cp.capslock(txtComplementoAddCliente);
        txtBairroAddCliente.requestFocus();

    }//GEN-LAST:event_txtComplementoAddClienteActionPerformed

    private void txtBairroAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroAddClienteActionPerformed
        cp.capslock(txtBairroAddCliente);
        cbSexoAddCliente.requestFocus();
    }//GEN-LAST:event_txtBairroAddClienteActionPerformed

    private void txtDataNascAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascAddClienteActionPerformed

        txtTelefone1AddCliente.requestFocus();

    }//GEN-LAST:event_txtDataNascAddClienteActionPerformed

    private void txtTelefone2AddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone2AddClienteActionPerformed

        bSalvarCadastroAddClienteActionPerformed(evt);

    }//GEN-LAST:event_txtTelefone2AddClienteActionPerformed

    private void txtTelefone1AddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone1AddClienteActionPerformed
        txtTelefone2AddCliente.requestFocus();
    }//GEN-LAST:event_txtTelefone1AddClienteActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed

        ResultSet rs = clienteControl.bucarByCpf(txtCpfAddCliente.getText());
        cliente = null;
        try {
            if (rs.next()) {
                cliente = new Cliente(rs.getInt("id"), rs.getString("nome"),
                        rs.getString("endereco"), rs.getString("bairro"),
                        rs.getString("complemento"), rs.getString("telefone2"),
                        rs.getString("cpf"), rs.getString("telefone1"),
                        rs.getDate("datanascimento"), rs.getString("sexo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAddCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clienteControl.excluirCliente(cliente);


    }//GEN-LAST:event_bExcluirActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        ResultSet rs = clienteControl.bucarByCpf(txtCpfAddCliente.getText());
        cliente = null;
        try {
            if (rs.next()) {
                cliente = new Cliente(rs.getInt("id"), txtNomeAddCliente.getText(), txtEnderecoAddCliente.getText(), txtBairroAddCliente.getText(), txtComplementoAddCliente.getText(), txtTelefone2AddCliente.getText(), txtCpfAddCliente.getText(), txtTelefone1AddCliente.getText(), rs.getDate("datanascimento"), cbSexoAddCliente.getSelectedItem().toString());
//                cliente = new Cliente(rs.getInt("id"), txtNomeAddCliente.getText(),
//                        txtEnderecoAddCliente.getText(), txtBairroAddCliente.getText(),
//                        txtComplementoAddCliente.getText(), txtTelefone2AddCliente.getText(),
//                        rs.getString("cpf"), txtTelefone1AddCliente.getText(),
//                        rs.getDate("datanascimento"), cbSexoAddCliente.getSelectedItem());
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAddCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clienteControl.atualizarCliente(cliente);
    }//GEN-LAST:event_bAtualizarActionPerformed

>>>>>>> origin/novaRamificacao

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bLimparAddCliente;
    public javax.swing.JButton bSalvarCadastroAddCliente;
    private javax.swing.JButton bVoltarAddCliente;
    private javax.swing.JComboBox cbSexoAddCliente;
    private javax.swing.JLabel lbBairroAddCliente;
    private javax.swing.JLabel lbComplementoAddCliente;
    private javax.swing.JLabel lbDataNascAddCliente;
    private javax.swing.JLabel lbEnderecoAddCliente;
    private javax.swing.JLabel lbNomeAddCdiente;
    private javax.swing.JLabel lbSexoAddCliente;
    private javax.swing.JLabel lbTelefone1AddCliente;
    private javax.swing.JLabel lbTelefone2AddCliente;
    private javax.swing.JLabel lbTituloAddCliente;
    private javax.swing.JLabel lbcpfAddCliente;
    private javax.swing.JTextField txtBairroAddCliente;
    private javax.swing.JTextField txtComplementoAddCliente;
    private javax.swing.JFormattedTextField txtCpfAddCliente;
    private javax.swing.JFormattedTextField txtDataNascAddCliente;
    private javax.swing.JTextField txtEnderecoAddCliente;
    private javax.swing.JTextField txtNomeAddCliente;
    private javax.swing.JFormattedTextField txtTelefone1AddCliente;
    private javax.swing.JFormattedTextField txtTelefone2AddCliente;
    // End of variables declaration//GEN-END:variables

    public void setTxtBairroAddCliente(String txtBairroAddCliente) {
        this.txtBairroAddCliente.setText(txtBairroAddCliente);
//        this.
    }

    public void setTxtComplementoAddCliente(String txtComplementoAddCliente) {
        this.txtComplementoAddCliente.setText(txtComplementoAddCliente);
    }

    public void setTxtCpfAddCliente(String txtCpfAddCliente) {
        this.txtCpfAddCliente.setText(txtCpfAddCliente);
    }
    
    public void setNoEditCPf(boolean estado) {
        this.txtCpfAddCliente.setEditable(estado);
    }

    public void setTxtDataNascAddCliente(String txtDataNascAddCliente) {
        this.txtDataNascAddCliente.setText(txtDataNascAddCliente);
    }

    public void setTxtEnderecoAddCliente(String txtEnderecoAddCliente) {
        this.txtEnderecoAddCliente.setText(txtEnderecoAddCliente);
    }

    public void setTxtNomeAddCliente(String txtNomeAddCliente) {
        this.txtNomeAddCliente.setText(txtNomeAddCliente);
    }

    public void setTxtTelefone1AddCliente(String txtTelefone1AddCliente) {
        this.txtTelefone1AddCliente.setText(txtTelefone1AddCliente);
    }

    public void setTxtTelefone2AddCliente(String txtTelefone2AddCliente) {
        this.txtTelefone2AddCliente.setText(txtTelefone2AddCliente);
    }

    public void setCbSexoAddCliente(String cbSexoAddCliente) {
        this.cbSexoAddCliente.setSelectedItem(cbSexoAddCliente);
    }

    public void setbEnableExcluir(boolean estado) {
        this.bExcluir.setEnabled(estado);
    }
    
    public void setbEnableAtualizar(boolean estado) {
        this.bAtualizar.setEnabled(estado);
    }
    
    public void setbEnableSalvar(boolean estado) {
        this.bSalvarCadastroAddCliente.setEnabled(estado);
    }
    
}
