/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.view;

import br.edu.uesb.petshop.control.TelaLoginControl;
import br.edu.uesb.petshop.enumerado.EnumView;
import br.edu.uesb.petshop.model.PetShop;

/**
 *
 * @author matheus
 */
public class TelaMenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloMenuPrincipal = new javax.swing.JLabel();
        bAnimaisMenuPrincipal = new javax.swing.JButton();
        bClientesMenuPrincipal = new javax.swing.JButton();
        bFuncionarioMenuPrincipal = new javax.swing.JButton();
        bServicosMenuPrincipal = new javax.swing.JButton();
        bLogoutMenuPrincipal = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        lbTituloMenuPrincipal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuPrincipal.setText("ADMIN");

        bAnimaisMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/77.png"))); // NOI18N
        bAnimaisMenuPrincipal.setText("ANIMAIS");
        bAnimaisMenuPrincipal.setMaximumSize(new java.awt.Dimension(122, 26));
        bAnimaisMenuPrincipal.setMinimumSize(new java.awt.Dimension(122, 26));
        bAnimaisMenuPrincipal.setPreferredSize(new java.awt.Dimension(122, 26));
        bAnimaisMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnimaisMenuPrincipalActionPerformed(evt);
            }
        });

        bClientesMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/13.png"))); // NOI18N
        bClientesMenuPrincipal.setToolTipText("");
        bClientesMenuPrincipal.setLabel("CLIENTES");
        bClientesMenuPrincipal.setMaximumSize(new java.awt.Dimension(122, 26));
        bClientesMenuPrincipal.setMinimumSize(new java.awt.Dimension(122, 26));
        bClientesMenuPrincipal.setPreferredSize(new java.awt.Dimension(122, 26));
        bClientesMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesMenuPrincipalActionPerformed(evt);
            }
        });

        bFuncionarioMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/14.png"))); // NOI18N
        bFuncionarioMenuPrincipal.setText("FUNCIONÁRIOS");
        bFuncionarioMenuPrincipal.setMaximumSize(new java.awt.Dimension(122, 26));
        bFuncionarioMenuPrincipal.setMinimumSize(new java.awt.Dimension(122, 26));
        bFuncionarioMenuPrincipal.setPreferredSize(new java.awt.Dimension(122, 26));
        bFuncionarioMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFuncionarioMenuPrincipalActionPerformed(evt);
            }
        });

        bServicosMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/9.png"))); // NOI18N
        bServicosMenuPrincipal.setText("SERVIÇOS");
        bServicosMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bServicosMenuPrincipalActionPerformed(evt);
            }
        });

        bLogoutMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/52.png"))); // NOI18N
        bLogoutMenuPrincipal.setText("LOGOUT");
        bLogoutMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloMenuPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLogoutMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bClientesMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(bFuncionarioMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAnimaisMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(bServicosMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTituloMenuPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAnimaisMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(bClientesMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bServicosMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(bFuncionarioMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(bLogoutMenuPrincipal)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAnimaisMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnimaisMenuPrincipalActionPerformed

        PetShop.tela.showView(EnumView.TELAANIMAL);

    }//GEN-LAST:event_bAnimaisMenuPrincipalActionPerformed

    public void setTipoMenu(TelaLoginControl.EnumLogin tipo) {
        if (tipo == TelaLoginControl.EnumLogin.LOGIN_FUNCIONARIO) {
            lbTituloMenuPrincipal.setText("FUNCIONARIO");
            bFuncionarioMenuPrincipal.setEnabled(false);
        } else if (tipo == TelaLoginControl.EnumLogin.LOGIN_ADMIN) {
            lbTituloMenuPrincipal.setText("ADMIN");
            bFuncionarioMenuPrincipal.setEnabled(true);
        }

    }

    private void bClientesMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesMenuPrincipalActionPerformed
       
        PetShop.tela.showView(EnumView.TELACLIENTE);
        
    }//GEN-LAST:event_bClientesMenuPrincipalActionPerformed

    private void bFuncionarioMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFuncionarioMenuPrincipalActionPerformed

        PetShop.tela.showView(EnumView.TELAFUNCIONARIO);

    }//GEN-LAST:event_bFuncionarioMenuPrincipalActionPerformed

    private void bServicosMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bServicosMenuPrincipalActionPerformed

        PetShop.tela.showView(EnumView.TELAATENDIMENTO);

    }//GEN-LAST:event_bServicosMenuPrincipalActionPerformed

    private void bLogoutMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMenuPrincipalActionPerformed

        PetShop.tela.showView(EnumView.TELALOGIN);

    }//GEN-LAST:event_bLogoutMenuPrincipalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnimaisMenuPrincipal;
    private javax.swing.JButton bClientesMenuPrincipal;
    private javax.swing.JButton bFuncionarioMenuPrincipal;
    private javax.swing.JButton bLogoutMenuPrincipal;
    private javax.swing.JButton bServicosMenuPrincipal;
    private javax.swing.JLabel lbTituloMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
