/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.view;

import br.edu.uesb.petshop.enumerado.EnumView;
import br.edu.uesb.petshop.model.PetShop;

/**
 *
 * @author matheus
 */
public class TelaMenuFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form TelaMenuFuncionario
     */
    public TelaMenuFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloMenuFuncionario = new javax.swing.JLabel();
        bVoltarMenuFuncionario = new javax.swing.JButton();
        bBuscarFuncionario = new javax.swing.JButton();
        bNovoFuncionario = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        lbTituloMenuFuncionario.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuFuncionario.setText("FUNCIONÁRIO");

        bVoltarMenuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/15.png"))); // NOI18N
        bVoltarMenuFuncionario.setText("VOLTAR");
        bVoltarMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuFuncionarioActionPerformed(evt);
            }
        });

        bBuscarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N
        bBuscarFuncionario.setText("<HTML><BODY>BUSCAR FUNCIONÁRIO</BODY></HTML>");
        bBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarFuncionarioActionPerformed(evt);
            }
        });

        bNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/14.png"))); // NOI18N
        bNovoFuncionario.setText("<HTML><BODY>NOVO FUNCIONÁRIO</BODY></HTML>");
        bNovoFuncionario.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoFuncionario.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoFuncionario.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbTituloMenuFuncionario)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bNovoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(bBuscarFuncionario)))
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bVoltarMenuFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTituloMenuFuncionario)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bBuscarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(bNovoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addComponent(bVoltarMenuFuncionario)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuFuncionarioActionPerformed
        
        PetShop.tela.showView(EnumView.TELAPRINCIPAL);

    }//GEN-LAST:event_bVoltarMenuFuncionarioActionPerformed

    private void bNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoFuncionarioActionPerformed
       
        PetShop.tela.showView(EnumView.TELAADDFUNCIONARIO);
        
    }//GEN-LAST:event_bNovoFuncionarioActionPerformed

    private void bBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarFuncionarioActionPerformed

        PetShop.tela.showView(EnumView.TELABUSCARFUNCIONARIO);
        
    }//GEN-LAST:event_bBuscarFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarFuncionario;
    private javax.swing.JButton bNovoFuncionario;
    private javax.swing.JButton bVoltarMenuFuncionario;
    private javax.swing.JLabel lbTituloMenuFuncionario;
    // End of variables declaration//GEN-END:variables
}
