/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

import enumerado.EnumView;
import javax.swing.JPanel;

/**
 *
 * @author matheus
 */
public class BarraDeMenu extends javax.swing.JFrame {

    TelaNovoAtendimento telaadd;
 
    
    /**
     * Creates new form BarraDeMenu
     */
    public BarraDeMenu() {
        initComponents();
        
    }

    
    public void showView(EnumView view){
        switch (view) {
            case LOGIN:
                
                break;
            case SERVICO: 
                setPanel(telaadd);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bmBarraMenu = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miAnimal = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        miBuscarCliente = new javax.swing.JMenuItem();
        mAnimais = new javax.swing.JMenu();
        miBuscarAnimal = new javax.swing.JMenuItem();
        mAtendimento = new javax.swing.JMenu();
        miOrcamento = new javax.swing.JMenuItem();
        miNovoAtendimento = new javax.swing.JMenuItem();
        miContultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 150, 0, 0));

        mCadastro.setText("Cadastro");
        mCadastro.setEnabled(false);

        miAnimal.setText("Animal");
        miAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnimalActionPerformed(evt);
            }
        });
        mCadastro.add(miAnimal);

        miCliente.setText("Cliente");
        mCadastro.add(miCliente);

        bmBarraMenu.add(mCadastro);

        mClientes.setText("Clientes");
        mClientes.setEnabled(false);

        miBuscarCliente.setText("Buscar");
        mClientes.add(miBuscarCliente);

        bmBarraMenu.add(mClientes);

        mAnimais.setText("Animais");
        mAnimais.setEnabled(false);

        miBuscarAnimal.setText("Buscar");
        mAnimais.add(miBuscarAnimal);

        bmBarraMenu.add(mAnimais);

        mAtendimento.setText("Atendimento");
        mAtendimento.setEnabled(false);

        miOrcamento.setText("Orçamento");
        mAtendimento.add(miOrcamento);

        miNovoAtendimento.setText("Novo Atendimento");
        mAtendimento.add(miNovoAtendimento);

        miContultar.setText("Consultar");
        miContultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContultarActionPerformed(evt);
            }
        });
        mAtendimento.add(miContultar);

        bmBarraMenu.add(mAtendimento);

        setJMenuBar(bmBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAnimalActionPerformed

    private void miContultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miContultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarraDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarraDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarraDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarraDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarraDeMenu().setVisible(true);
            }
        });
    }
    
    public void setPanel(javax.swing.JPanel panel) {
        setContentPane(panel);
        pack();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bmBarraMenu;
    private javax.swing.JMenu mAnimais;
    private javax.swing.JMenu mAtendimento;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem miAnimal;
    private javax.swing.JMenuItem miBuscarAnimal;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miContultar;
    private javax.swing.JMenuItem miNovoAtendimento;
    private javax.swing.JMenuItem miOrcamento;
    // End of variables declaration//GEN-END:variables
}
