/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates   
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

import br.edu.uesb.petshop.dao.ConexaoPostgreSQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public void capslock(final javax.swing.JTextField txt) {
        txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt.setText(txt.getText().toUpperCase());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        pMenuLogin = new javax.swing.JPanel();
        lbTituloMenuLogin = new javax.swing.JLabel();
        txtLoginMenuLogin = new javax.swing.JTextField();
        lbLoginMenuLogin = new javax.swing.JLabel();
        lbSenhaMenuLogin = new javax.swing.JLabel();
        bEntrarMenuLogin = new javax.swing.JButton();
        bSairMenuLogin = new javax.swing.JButton();
        txtSenhaMenuLogin = new javax.swing.JPasswordField();
        pLoginIncorretoMenuLogin = new javax.swing.JPanel();
        lbLoginIncorretoMenuLogin = new javax.swing.JLabel();
        pMenuPrincipal = new javax.swing.JPanel();
        lbTituloMenuPrincipal = new javax.swing.JLabel();
        bAnimaisMenuPrincipal = new javax.swing.JButton();
        bClientesMenuPrincipal = new javax.swing.JButton();
        bFuncionarioMenuPrincipal = new javax.swing.JButton();
        bServicosMenuPrincipal = new javax.swing.JButton();
        bLogoutMenuPrincipal = new javax.swing.JButton();
        pMenuAnimal = new javax.swing.JPanel();
        lbTituloMenuAnimal = new javax.swing.JLabel();
        bVoltarMenuAnimal = new javax.swing.JButton();
        bBuscarAnimal = new javax.swing.JButton();
        bNovoAnimal = new javax.swing.JButton();
        pMenuAddAnimal = new javax.swing.JPanel();
        bVoltarAddAnimal = new javax.swing.JButton();
        lbTituloAddAnimal = new javax.swing.JLabel();
        bLimparAddAnimal = new javax.swing.JButton();
        bSalvarCadastroAddAnimal = new javax.swing.JButton();
        rbMachoAddAnimal = new javax.swing.JRadioButton();
        rbFemeaAddAnimal = new javax.swing.JRadioButton();
        txtNomeAddAnimal = new javax.swing.JTextField();
        cbEspecieAddAnimal = new javax.swing.JComboBox();
        cbDonoAddAnimal = new javax.swing.JComboBox();
        lbNomeAddAnimal = new javax.swing.JLabel();
        lbSexoAddAnimal = new javax.swing.JLabel();
        lbEspecieAddAnimal = new javax.swing.JLabel();
        lbRacaAddAnimal = new javax.swing.JLabel();
        lbDonoAddAnimal = new javax.swing.JLabel();
        txtRacaAddAnimal = new javax.swing.JTextField();
        pMenuCliente = new javax.swing.JPanel();
        lbTituloMenuCliente = new javax.swing.JLabel();
        bVoltarMenuCliente = new javax.swing.JButton();
        bBuscarCliente = new javax.swing.JButton();
        bNovoCliente = new javax.swing.JButton();
        pMenuAddCliente = new javax.swing.JPanel();
        lbTituloAddCliente = new javax.swing.JLabel();
        txtNomeAddCliente = new javax.swing.JTextField();
        lbNomeAddCdiente = new javax.swing.JLabel();
        txtEnderecoAddCliente = new javax.swing.JTextField();
        lbEnderecoAddCliente = new javax.swing.JLabel();
        lbBairroAddCliente = new javax.swing.JLabel();
        txtBairroAddCliente = new javax.swing.JTextField();
        lbComplementoAddCliente = new javax.swing.JLabel();
        txtComplementoAddCliente = new javax.swing.JTextField();
        lbSexoAddCliente = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        lbcpfAddCliente = new javax.swing.JLabel();
        txtCpfAddCliente = new javax.swing.JFormattedTextField();
        lbDataNascAddCliente = new javax.swing.JLabel();
        txtDataNascAddCliente = new javax.swing.JFormattedTextField();
        lbTelefone1AddCliente = new javax.swing.JLabel();
        txtTelefone1AddCliente = new javax.swing.JFormattedTextField();
        lbTelefone2AddCliente = new javax.swing.JLabel();
        txtTelefone2AddCliente = new javax.swing.JFormattedTextField();
        bLimparAddCliente = new javax.swing.JButton();
        bSalvarCadastroAddCliente = new javax.swing.JButton();
        bVoltarAddCliente = new javax.swing.JButton();
        lbFaltaMensagemAddCliente = new javax.swing.JLabel();
        pMenuFuncionario = new javax.swing.JPanel();
        lbTituloMenuFuncionario = new javax.swing.JLabel();
        bVoltarMenuFuncionario = new javax.swing.JButton();
        bBuscarFuncionario = new javax.swing.JButton();
        bNovoFuncionario = new javax.swing.JButton();
        pMenuServico = new javax.swing.JPanel();
        lbTituloMenuServico = new javax.swing.JLabel();
        bVoltarMenuServico = new javax.swing.JButton();
        bBuscarServico = new javax.swing.JButton();
        bNovoServico = new javax.swing.JButton();
        bmBarraMenu = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miAnimal = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        miBuscarCliente = new javax.swing.JMenuItem();
        mAnimais = new javax.swing.JMenu();
        miBuscarAnimal = new javax.swing.JMenuItem();
        mAtendimento = new javax.swing.JMenu();
        miOrcamento = new javax.swing.JMenuItem();
        miNovoAtendimento = new javax.swing.JMenuItem();
        miContultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetShop");
        setBounds(new java.awt.Rectangle(0, 0, 90, 150));
        setMinimumSize(new java.awt.Dimension(300, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));

        pMenuLogin.setEnabled(false);
        pMenuLogin.setPreferredSize(new java.awt.Dimension(700, 350));

        lbTituloMenuLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloMenuLogin.setText("PET SHOP");

        txtLoginMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginMenuLoginActionPerformed(evt);
            }
        });

        lbLoginMenuLogin.setText("Login:");

        lbSenhaMenuLogin.setText("Senha:");

        bEntrarMenuLogin.setText("Entrar");
        bEntrarMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarMenuLoginActionPerformed(evt);
            }
        });

        bSairMenuLogin.setText("Sair");
        bSairMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairMenuLoginActionPerformed(evt);
            }
        });

        txtSenhaMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaMenuLoginActionPerformed(evt);
            }
        });

        pLoginIncorretoMenuLogin.setBackground(new java.awt.Color(255, 0, 0));
        pLoginIncorretoMenuLogin.setVisible(false);

        lbLoginIncorretoMenuLogin.setForeground(new java.awt.Color(255, 204, 204));
        lbLoginIncorretoMenuLogin.setText("Login incorreto, por favor tente novamente");

        javax.swing.GroupLayout pLoginIncorretoMenuLoginLayout = new javax.swing.GroupLayout(pLoginIncorretoMenuLogin);
        pLoginIncorretoMenuLogin.setLayout(pLoginIncorretoMenuLoginLayout);
        pLoginIncorretoMenuLoginLayout.setHorizontalGroup(
            pLoginIncorretoMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginIncorretoMenuLoginLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(lbLoginIncorretoMenuLogin)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        pLoginIncorretoMenuLoginLayout.setVerticalGroup(
            pLoginIncorretoMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLoginIncorretoMenuLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pMenuLoginLayout = new javax.swing.GroupLayout(pMenuLogin);
        pMenuLogin.setLayout(pMenuLoginLayout);
        pMenuLoginLayout.setHorizontalGroup(
            pMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLoginIncorretoMenuLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pMenuLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(pMenuLoginLayout.createSequentialGroup()
                        .addComponent(bSairMenuLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(bEntrarMenuLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pMenuLoginLayout.createSequentialGroup()
                        .addComponent(lbLoginMenuLogin)
                        .addGap(18, 18, 18)
                        .addComponent(txtLoginMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMenuLoginLayout.createSequentialGroup()
                        .addComponent(lbSenhaMenuLogin)
                        .addGap(12, 12, 12)
                        .addComponent(txtSenhaMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTituloMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuLoginLayout.setVerticalGroup(
            pMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenuLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                .addGroup(pMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLoginMenuLogin))
                .addGap(18, 18, 18)
                .addGroup(pMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenhaMenuLogin))
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(pLoginIncorretoMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(pMenuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEntrarMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSairMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pMenuPrincipal.setVisible(false);

        lbTituloMenuPrincipal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuPrincipal.setText("ADMIN");

        bAnimaisMenuPrincipal.setText("ANIMAIS");
        bAnimaisMenuPrincipal.setMaximumSize(new java.awt.Dimension(122, 26));
        bAnimaisMenuPrincipal.setMinimumSize(new java.awt.Dimension(122, 26));
        bAnimaisMenuPrincipal.setPreferredSize(new java.awt.Dimension(122, 26));
        bAnimaisMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnimaisMenuPrincipalActionPerformed(evt);
            }
        });

        bClientesMenuPrincipal.setToolTipText("");
        bClientesMenuPrincipal.setLabel("CLIENTES");
        bClientesMenuPrincipal.setMaximumSize(new java.awt.Dimension(122, 26));
        bClientesMenuPrincipal.setMinimumSize(new java.awt.Dimension(122, 26));
        bClientesMenuPrincipal.setPreferredSize(new java.awt.Dimension(122, 26));
        bClientesMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesMenuPrincipalActionPerformed(evt);
            }
        });

        bFuncionarioMenuPrincipal.setText("FUNCIONÁRIOS");
        bFuncionarioMenuPrincipal.setMaximumSize(new java.awt.Dimension(122, 26));
        bFuncionarioMenuPrincipal.setMinimumSize(new java.awt.Dimension(122, 26));
        bFuncionarioMenuPrincipal.setPreferredSize(new java.awt.Dimension(122, 26));
        bFuncionarioMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFuncionarioMenuPrincipalActionPerformed(evt);
            }
        });

        bServicosMenuPrincipal.setText("SERVIÇOS");
        bServicosMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bServicosMenuPrincipalActionPerformed(evt);
            }
        });

        bLogoutMenuPrincipal.setText("LOGOUT");
        bLogoutMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuPrincipalLayout = new javax.swing.GroupLayout(pMenuPrincipal);
        pMenuPrincipal.setLayout(pMenuPrincipalLayout);
        pMenuPrincipalLayout.setHorizontalGroup(
            pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloMenuPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bClientesMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bFuncionarioMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAnimaisMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bServicosMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(bLogoutMenuPrincipal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuPrincipalLayout.setVerticalGroup(
            pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenuPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bClientesMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAnimaisMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bFuncionarioMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bServicosMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bLogoutMenuPrincipal)
                .addContainerGap())
        );

        pMenuAnimal.setVisible(false);
        pMenuAnimal.setPreferredSize(new java.awt.Dimension(700, 350));

        lbTituloMenuAnimal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuAnimal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuAnimal.setText("ANIMAL");

        bVoltarMenuAnimal.setText("VOLTAR");
        bVoltarMenuAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuAnimalActionPerformed(evt);
            }
        });

        bBuscarAnimal.setText("BUSCAR ANIMAL");

        bNovoAnimal.setText("NOVO ANIMAL");
        bNovoAnimal.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuAnimalLayout = new javax.swing.GroupLayout(pMenuAnimal);
        pMenuAnimal.setLayout(pMenuAnimalLayout);
        pMenuAnimalLayout.setHorizontalGroup(
            pMenuAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuAnimalLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(pMenuAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuAnimalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTituloMenuAnimal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMenuAnimalLayout.createSequentialGroup()
                        .addComponent(bNovoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addGroup(pMenuAnimalLayout.createSequentialGroup()
                        .addComponent(bVoltarMenuAnimal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pMenuAnimalLayout.setVerticalGroup(
            pMenuAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenuAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(pMenuAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNovoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(bBuscarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(bVoltarMenuAnimal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bVoltarAddAnimal.setText("<html><body>VOLTAR</body></html>");
        bVoltarAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarAddAnimalActionPerformed(evt);
            }
        });

        lbTituloAddAnimal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloAddAnimal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloAddAnimal.setText("Animal");

        bLimparAddAnimal.setText("LIMPAR");
        bLimparAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparAddAnimalActionPerformed(evt);
            }
        });

        bSalvarCadastroAddAnimal.setText("<html><body>SALVAR CADASTRO</body></html>");
        bSalvarCadastroAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarCadastroAddAnimalActionPerformed(evt);
            }
        });

        bgSexo.add(rbMachoAddAnimal);
        rbMachoAddAnimal.setText("Macho");
        rbMachoAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMachoAddAnimalActionPerformed(evt);
            }
        });
        rbMachoAddAnimal.setActionCommand("MACHO");

        bgSexo.add(rbFemeaAddAnimal);
        rbFemeaAddAnimal.setText("Fêmea");
        rbFemeaAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemeaAddAnimalActionPerformed(evt);
            }
        });
        rbFemeaAddAnimal.setActionCommand("FÊMEA");

        capslock(txtNomeAddAnimal);

        cbEspecieAddAnimal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "CACHORRO", "GATO", "CAVALO", "PASSARO", "VEADO(KURAS)", "POKÉMON(PEDRO)" }));

        cbDonoAddAnimal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cbDonoAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDonoAddAnimalActionPerformed(evt);
            }
        });

        lbNomeAddAnimal.setText("NOME:");

        lbSexoAddAnimal.setText("SEXO:");

        lbEspecieAddAnimal.setText("ESPECIE:");

        lbRacaAddAnimal.setText("RAÇA:");

        lbDonoAddAnimal.setText("DONO:");

        capslock(txtRacaAddAnimal);

        javax.swing.GroupLayout pMenuAddAnimalLayout = new javax.swing.GroupLayout(pMenuAddAnimal);
        pMenuAddAnimal.setLayout(pMenuAddAnimalLayout);
        pMenuAddAnimalLayout.setHorizontalGroup(
            pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuAddAnimalLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNomeAddAnimal)
                    .addComponent(lbSexoAddAnimal)
                    .addComponent(lbEspecieAddAnimal)
                    .addComponent(lbRacaAddAnimal)
                    .addComponent(lbDonoAddAnimal))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEspecieAddAnimal, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pMenuAddAnimalLayout.createSequentialGroup()
                        .addComponent(rbMachoAddAnimal)
                        .addGap(41, 41, 41)
                        .addComponent(rbFemeaAddAnimal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMenuAddAnimalLayout.createSequentialGroup()
                        .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLimparAddAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVoltarAddAnimal))
                        .addGap(18, 18, 18)
                        .addComponent(bSalvarCadastroAddAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addComponent(txtNomeAddAnimal)
                    .addComponent(cbDonoAddAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRacaAddAnimal))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuAddAnimalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAddAnimal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuAddAnimalLayout.setVerticalGroup(
            pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuAddAnimalLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lbTituloAddAnimal)
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeAddAnimal))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMachoAddAnimal)
                    .addComponent(rbFemeaAddAnimal)
                    .addComponent(lbSexoAddAnimal))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspecieAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEspecieAddAnimal))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRacaAddAnimal)
                    .addComponent(txtRacaAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDonoAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDonoAddAnimal))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(pMenuAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuAddAnimalLayout.createSequentialGroup()
                        .addComponent(bLimparAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVoltarAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bSalvarCadastroAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();
        try{
            ResultSet rs = query.executeQuery("SELECT nome FROM \"Cliente\"");

            while(rs.next()){
                cbDonoAddAnimal.addItem(rs.getString("nome"));
            }

        }catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            lbLoginIncorretoMenuLogin.setVisible(true);
        }

        pMenuCliente.setVisible(false);
        pMenuCliente.setPreferredSize(new java.awt.Dimension(700, 350));

        lbTituloMenuCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuCliente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuCliente.setText("CLIENTE");

        bVoltarMenuCliente.setText("VOLTAR");
        bVoltarMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuClienteActionPerformed(evt);
            }
        });

        bBuscarCliente.setText("BUSCAR CLIENTE");

        bNovoCliente.setText("NOVO CLIENTE");
        bNovoCliente.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoCliente.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoCliente.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuClienteLayout = new javax.swing.GroupLayout(pMenuCliente);
        pMenuCliente.setLayout(pMenuClienteLayout);
        pMenuClienteLayout.setHorizontalGroup(
            pMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuClienteLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(pMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTituloMenuCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMenuClienteLayout.createSequentialGroup()
                        .addComponent(bNovoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(pMenuClienteLayout.createSequentialGroup()
                        .addComponent(bVoltarMenuCliente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pMenuClienteLayout.setVerticalGroup(
            pMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenuCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(pMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNovoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(bBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(bVoltarMenuCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuAddCliente.setPreferredSize(new java.awt.Dimension(700, 350));
        pMenuAddCliente.setVisible(false);

        lbTituloAddCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloAddCliente.setText("ADICIONAR CLIENTE");

        capslock(txtNomeAddCliente);

        lbNomeAddCdiente.setText("Nome:");

        capslock(txtEnderecoAddCliente);

        lbEnderecoAddCliente.setText("Endereço:");

        lbBairroAddCliente.setText("Bairro:");

        capslock(txtBairroAddCliente);

        lbComplementoAddCliente.setText("Complemento:");

        capslock(txtComplementoAddCliente);

        lbSexoAddCliente.setText("Sexo:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });

        lbcpfAddCliente.setText("CPF:");

        try {
            txtCpfAddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbDataNascAddCliente.setText("Data Nasc.:");

        try {
            txtDataNascAddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone1AddCliente.setText("Telefone 1:");

        try {
            txtTelefone1AddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone2AddCliente.setText("Telefone 2:");

        try {
            txtTelefone2AddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bLimparAddCliente.setText("LIMPAR");
        bLimparAddCliente.setPreferredSize(new java.awt.Dimension(67, 27));
        bLimparAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparAddClienteActionPerformed(evt);
            }
        });

        bSalvarCadastroAddCliente.setText("SALVAR CADASTRO");
        bSalvarCadastroAddCliente.setPreferredSize(new java.awt.Dimension(4075, 27));
        bSalvarCadastroAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarCadastroAddClienteActionPerformed(evt);
            }
        });

        bVoltarAddCliente.setText("VOLTAR");
        bVoltarAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarAddClienteActionPerformed(evt);
            }
        });

        lbFaltaMensagemAddCliente.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaMensagemAddCliente.setText("Por favor preencha os campos restantes *");
        lbFaltaMensagemAddCliente.setVisible(false);

        javax.swing.GroupLayout pMenuAddClienteLayout = new javax.swing.GroupLayout(pMenuAddCliente);
        pMenuAddCliente.setLayout(pMenuAddClienteLayout);
        pMenuAddClienteLayout.setHorizontalGroup(
            pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuAddClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAddCliente)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuAddClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                        .addComponent(lbComplementoAddCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txtComplementoAddCliente))
                    .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                        .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnderecoAddCliente)
                            .addComponent(lbNomeAddCdiente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeAddCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                                .addComponent(txtEnderecoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbBairroAddCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuAddClienteLayout.createSequentialGroup()
                                .addComponent(lbFaltaMensagemAddCliente)
                                .addGap(6, 6, 6))))
                    .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                        .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                                .addComponent(lbSexoAddCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbcpfAddCliente))
                            .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                                .addComponent(lbTelefone2AddCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone2AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtCpfAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbDataNascAddCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataNascAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bLimparAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bVoltarAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(bSalvarCadastroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                        .addComponent(lbTelefone1AddCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone1AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        pMenuAddClienteLayout.setVerticalGroup(
            pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloAddCliente)
                .addGap(18, 18, 18)
                .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeAddCdiente))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnderecoAddCliente)
                    .addComponent(lbBairroAddCliente)
                    .addComponent(txtBairroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplementoAddCliente)
                    .addComponent(txtComplementoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcpfAddCliente)
                    .addComponent(txtCpfAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataNascAddCliente)
                    .addComponent(txtDataNascAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexoAddCliente))
                .addGap(39, 39, 39)
                .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                            .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbTelefone1AddCliente)
                                .addComponent(txtTelefone1AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pMenuAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTelefone2AddCliente)
                                .addComponent(txtTelefone2AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(bSalvarCadastroAddCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMenuAddClienteLayout.createSequentialGroup()
                        .addComponent(bLimparAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVoltarAddCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lbFaltaMensagemAddCliente)
                .addGap(0, 0, 0))
        );

        pMenuFuncionario.setVisible(false);
        pMenuFuncionario.setPreferredSize(new java.awt.Dimension(700, 350));

        lbTituloMenuFuncionario.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuFuncionario.setText("FUNCIONÁRIO");

        bVoltarMenuFuncionario.setText("VOLTAR");
        bVoltarMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuFuncionarioActionPerformed(evt);
            }
        });

        bBuscarFuncionario.setText("<HTML><BODY>BUSCAR FUNCIONÁRIO</BODY></HTML>");

        bNovoFuncionario.setText("<HTML><BODY>NOVO FUNCIONÁRIO</BODY></HTML>");
        bNovoFuncionario.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoFuncionario.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoFuncionario.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuFuncionarioLayout = new javax.swing.GroupLayout(pMenuFuncionario);
        pMenuFuncionario.setLayout(pMenuFuncionarioLayout);
        pMenuFuncionarioLayout.setHorizontalGroup(
            pMenuFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuFuncionarioLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(pMenuFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuFuncionarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTituloMenuFuncionario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMenuFuncionarioLayout.createSequentialGroup()
                        .addComponent(bNovoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addGroup(pMenuFuncionarioLayout.createSequentialGroup()
                        .addComponent(bVoltarMenuFuncionario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pMenuFuncionarioLayout.setVerticalGroup(
            pMenuFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenuFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(pMenuFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNovoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(bBuscarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(bVoltarMenuFuncionario)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pMenuServico.setVisible(false);
        pMenuServico.setPreferredSize(new java.awt.Dimension(700, 350));

        lbTituloMenuServico.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuServico.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuServico.setText("SERVIÇOS");

        bVoltarMenuServico.setText("VOLTAR");
        bVoltarMenuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuServicoActionPerformed(evt);
            }
        });

        bBuscarServico.setText("<HTML><BODY>BUSCAR SERVIÇO</BODY></HTML>");

        bNovoServico.setText("<HTML><BODY>NOVO SERVIÇO</BODY></HTML>");
        bNovoServico.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoServico.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoServico.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuServicoLayout = new javax.swing.GroupLayout(pMenuServico);
        pMenuServico.setLayout(pMenuServicoLayout);
        pMenuServicoLayout.setHorizontalGroup(
            pMenuServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuServicoLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(pMenuServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuServicoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTituloMenuServico)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMenuServicoLayout.createSequentialGroup()
                        .addComponent(bNovoServico, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscarServico, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addGroup(pMenuServicoLayout.createSequentialGroup()
                        .addComponent(bVoltarMenuServico)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        pMenuServicoLayout.setVerticalGroup(
            pMenuServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenuServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(pMenuServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNovoServico, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(bBuscarServico, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(bVoltarMenuServico)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        mCadastro.setText("Cadastro");
        mCadastro.setEnabled(false);

        miAnimal.setText("Animal");
        miAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnimalActionPerformed(evt);
            }
        });
        mCadastro.add(miAnimal);

        miCliente.setText("Cliente");
        mCadastro.add(miCliente);

        bmBarraMenu.add(mCadastro);

        mClientes.setText("Clientes");
        mClientes.setEnabled(false);

        miBuscarCliente.setText("Buscar");
        mClientes.add(miBuscarCliente);

        bmBarraMenu.add(mClientes);

        mAnimais.setText("Animais");
        mAnimais.setEnabled(false);

        miBuscarAnimal.setText("Buscar");
        mAnimais.add(miBuscarAnimal);

        bmBarraMenu.add(mAnimais);

        mAtendimento.setText("Atendimento");
        mAtendimento.setEnabled(false);

        miOrcamento.setText("Orçamento");
        mAtendimento.add(miOrcamento);

        miNovoAtendimento.setText("Novo Atendimento");
        mAtendimento.add(miNovoAtendimento);

        miContultar.setText("Consultar");
        miContultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContultarActionPerformed(evt);
            }
        });
        mAtendimento.add(miContultar);

        bmBarraMenu.add(mAtendimento);

        setJMenuBar(bmBarraMenu);

        pMenuAddAnimal.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenuLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuAddAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenuLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuAnimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuAddAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pMenuServico, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAnimalActionPerformed

    private void miContultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miContultarActionPerformed

    private void txtSenhaMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaMenuLoginActionPerformed
        bEntrarMenuLoginActionPerformed(evt);
    }//GEN-LAST:event_txtSenhaMenuLoginActionPerformed

    private void bSairMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairMenuLoginActionPerformed
        this.fechar();
    }//GEN-LAST:event_bSairMenuLoginActionPerformed

    private void bEntrarMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarMenuLoginActionPerformed
        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();
        int cont = 0;

        try {

            ResultSet rs = query.executeQuery("SELECT id, login, senha, nivel FROM \"Admin\""
                    + "WHERE login = '" + txtLoginMenuLogin.getText() + "' ");

            while (rs.next()) {
                cont++;
                rs = query.executeQuery("SELECT id, login, senha, nivel FROM \"Admin\""
                        + "WHERE senha = '" + txtSenhaMenuLogin.getText() + "' ");

                while (rs.next()) {
                    if (rs.getString("login").equals(txtLoginMenuLogin.getText())) {
                        if (rs.getInt("nivel") == 1) {
                            lbTituloMenuPrincipal.setText("FUNCIONARIO");
                            bFuncionarioMenuPrincipal.setEnabled(false);
                        } else {
                            lbTituloMenuPrincipal.setText("ADMIN");
                            bFuncionarioMenuPrincipal.setEnabled(true);
                        }
                        pLoginIncorretoMenuLogin.setVisible(false);
                        cont++;
                        pMenuLogin.setVisible(false);
                        pMenuPrincipal.setVisible(true);
                        mAnimais.setEnabled(true);
                        mClientes.setEnabled(true);
                        mAtendimento.setEnabled(true);
                        mCadastro.setEnabled(true);
                    }
                }
            }

            if (cont == 0) {
                pLoginIncorretoMenuLogin.setVisible(true);
                lbLoginIncorretoMenuLogin.setText("Login invalido, por favor tente novamente");
            } else if (cont == 1) {
                pLoginIncorretoMenuLogin.setVisible(true);
                lbLoginIncorretoMenuLogin.setText("Senha invalida, por favor tente novamente");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            lbLoginIncorretoMenuLogin.setVisible(true);
        }
    }//GEN-LAST:event_bEntrarMenuLoginActionPerformed

    private void txtLoginMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginMenuLoginActionPerformed
        txtSenhaMenuLogin.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginMenuLoginActionPerformed

    private void bVoltarAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarAddAnimalActionPerformed
        pMenuAddAnimal.setVisible(false);
        pMenuAnimal.setVisible(true);
        bLimparAddAnimalActionPerformed(evt);
    }//GEN-LAST:event_bVoltarAddAnimalActionPerformed

    private void bLimparAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparAddAnimalActionPerformed
        txtNomeAddAnimal.setText("");
        txtRacaAddAnimal.setText("");
        cbEspecieAddAnimal.setSelectedItem("-");
        cbDonoAddAnimal.setSelectedItem("-");
        bgSexo.clearSelection();
    }//GEN-LAST:event_bLimparAddAnimalActionPerformed

    private void rbMachoAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMachoAddAnimalActionPerformed

    }//GEN-LAST:event_rbMachoAddAnimalActionPerformed

    private void rbFemeaAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemeaAddAnimalActionPerformed

    }//GEN-LAST:event_rbFemeaAddAnimalActionPerformed

    private void cbDonoAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDonoAddAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDonoAddAnimalActionPerformed

    private void bLogoutMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMenuPrincipalActionPerformed
        pMenuPrincipal.setVisible(false);
        pMenuLogin.setVisible(true);
        txtLoginMenuLogin.setText("");
        txtSenhaMenuLogin.setText("");
        mAnimais.setEnabled(false);
        mClientes.setEnabled(false);
        mAtendimento.setEnabled(false);
        mCadastro.setEnabled(false);
    }//GEN-LAST:event_bLogoutMenuPrincipalActionPerformed

    private void bClientesMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesMenuPrincipalActionPerformed
        pMenuPrincipal.setVisible(false);
        pMenuCliente.setVisible(true);
    }//GEN-LAST:event_bClientesMenuPrincipalActionPerformed

    private void bAnimaisMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnimaisMenuPrincipalActionPerformed
        pMenuAnimal.setVisible(true);
        pMenuPrincipal.setVisible(false);
    }//GEN-LAST:event_bAnimaisMenuPrincipalActionPerformed

    private void bVoltarMenuAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuAnimalActionPerformed
        pMenuPrincipal.setVisible(true);
        pMenuAnimal.setVisible(false);
    }//GEN-LAST:event_bVoltarMenuAnimalActionPerformed

    private void bNovoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoAnimalActionPerformed
        pMenuAddAnimal.setVisible(true);
        pMenuAnimal.setVisible(false);
    }//GEN-LAST:event_bNovoAnimalActionPerformed

    private void bVoltarMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuClienteActionPerformed
        pMenuCliente.setVisible(false);
        pMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_bVoltarMenuClienteActionPerformed

    private void bNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoClienteActionPerformed
        pMenuCliente.setVisible(false);
        pMenuAddCliente.setVisible(true);
    }//GEN-LAST:event_bNovoClienteActionPerformed

    private void bSalvarCadastroAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarCadastroAddAnimalActionPerformed
        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();

        //add
        try {
            query.executeUpdate("INSERT INTO \"Animal\"(\n"
                    + "            nome, sexo, especie, raca, dono)\n"
                    + "    VALUES ('" + txtNomeAddAnimal.getText() + "','" + bgSexo.getSelection().getActionCommand() + "','" + cbEspecieAddAnimal.getSelectedItem()
                    + "','" + txtRacaAddAnimal.getText() + "','" + cbDonoAddAnimal.getSelectedItem() + "');");

            JOptionPane.showMessageDialog(null, "Salvo com sucesso!", null, JOptionPane.PLAIN_MESSAGE, null);
            bLimparAddAnimalActionPerformed(evt);//limparcampos

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados ", "ERRO", JOptionPane.ERROR_MESSAGE, null);
        }

    }//GEN-LAST:event_bSalvarCadastroAddAnimalActionPerformed

    private void bServicosMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bServicosMenuPrincipalActionPerformed
        pMenuServico.setVisible(true);
        pMenuPrincipal.setVisible(false);
    }//GEN-LAST:event_bServicosMenuPrincipalActionPerformed

    private void bFuncionarioMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFuncionarioMenuPrincipalActionPerformed
        pMenuPrincipal.setVisible(false);
        pMenuFuncionario.setVisible(true);
    }//GEN-LAST:event_bFuncionarioMenuPrincipalActionPerformed

    private void bVoltarMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuFuncionarioActionPerformed
        pMenuFuncionario.setVisible(false);
        pMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_bVoltarMenuFuncionarioActionPerformed

    private void bNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNovoFuncionarioActionPerformed

    private void bVoltarMenuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuServicoActionPerformed
        pMenuServico.setVisible(false);
        pMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_bVoltarMenuServicoActionPerformed

    private void bNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNovoServicoActionPerformed

    private void bVoltarAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarAddClienteActionPerformed
        pMenuAddCliente.setVisible(false);
        pMenuCliente.setVisible(true);
        bLimparAddClienteActionPerformed(evt);
    }//GEN-LAST:event_bVoltarAddClienteActionPerformed

    private void bSalvarCadastroAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarCadastroAddClienteActionPerformed

    }//GEN-LAST:event_bSalvarCadastroAddClienteActionPerformed

    private void bLimparAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparAddClienteActionPerformed
        txtNomeAddCliente.setText("");
        txtEnderecoAddCliente.setText("");
        txtComplementoAddCliente.setText("");
        txtBairroAddCliente.setText("");
        txtCpfAddCliente.setText("");
        txtDataNascAddCliente.setText("");
        txtTelefone1AddCliente.setText("");
        txtTelefone2AddCliente.setText("");
        cbSexo.setSelectedItem(0);
    }//GEN-LAST:event_bLimparAddClienteActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnimaisMenuPrincipal;
    private javax.swing.JButton bBuscarAnimal;
    private javax.swing.JButton bBuscarCliente;
    private javax.swing.JButton bBuscarFuncionario;
    private javax.swing.JButton bBuscarServico;
    private javax.swing.JButton bClientesMenuPrincipal;
    private javax.swing.JButton bEntrarMenuLogin;
    private javax.swing.JButton bFuncionarioMenuPrincipal;
    private javax.swing.JButton bLimparAddAnimal;
    private javax.swing.JButton bLimparAddCliente;
    private javax.swing.JButton bLogoutMenuPrincipal;
    private javax.swing.JButton bNovoAnimal;
    private javax.swing.JButton bNovoCliente;
    private javax.swing.JButton bNovoFuncionario;
    private javax.swing.JButton bNovoServico;
    private javax.swing.JButton bSairMenuLogin;
    private javax.swing.JButton bSalvarCadastroAddAnimal;
    private javax.swing.JButton bSalvarCadastroAddCliente;
    private javax.swing.JButton bServicosMenuPrincipal;
    private javax.swing.JButton bVoltarAddAnimal;
    private javax.swing.JButton bVoltarAddCliente;
    private javax.swing.JButton bVoltarMenuAnimal;
    private javax.swing.JButton bVoltarMenuCliente;
    private javax.swing.JButton bVoltarMenuFuncionario;
    private javax.swing.JButton bVoltarMenuServico;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JMenuBar bmBarraMenu;
    private javax.swing.JComboBox cbDonoAddAnimal;
    private javax.swing.JComboBox cbEspecieAddAnimal;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JLabel lbBairroAddCliente;
    private javax.swing.JLabel lbComplementoAddCliente;
    private javax.swing.JLabel lbDataNascAddCliente;
    private javax.swing.JLabel lbDonoAddAnimal;
    private javax.swing.JLabel lbEnderecoAddCliente;
    private javax.swing.JLabel lbEspecieAddAnimal;
    private javax.swing.JLabel lbFaltaMensagemAddCliente;
    private javax.swing.JLabel lbLoginIncorretoMenuLogin;
    private javax.swing.JLabel lbLoginMenuLogin;
    private javax.swing.JLabel lbNomeAddAnimal;
    private javax.swing.JLabel lbNomeAddCdiente;
    private javax.swing.JLabel lbRacaAddAnimal;
    private javax.swing.JLabel lbSenhaMenuLogin;
    private javax.swing.JLabel lbSexoAddAnimal;
    private javax.swing.JLabel lbSexoAddCliente;
    private javax.swing.JLabel lbTelefone1AddCliente;
    private javax.swing.JLabel lbTelefone2AddCliente;
    private javax.swing.JLabel lbTituloAddAnimal;
    private javax.swing.JLabel lbTituloAddCliente;
    private javax.swing.JLabel lbTituloMenuAnimal;
    private javax.swing.JLabel lbTituloMenuCliente;
    private javax.swing.JLabel lbTituloMenuFuncionario;
    private javax.swing.JLabel lbTituloMenuLogin;
    private javax.swing.JLabel lbTituloMenuPrincipal;
    private javax.swing.JLabel lbTituloMenuServico;
    private javax.swing.JLabel lbcpfAddCliente;
    private javax.swing.JMenu mAnimais;
    private javax.swing.JMenu mAtendimento;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem miAnimal;
    private javax.swing.JMenuItem miBuscarAnimal;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miContultar;
    private javax.swing.JMenuItem miNovoAtendimento;
    private javax.swing.JMenuItem miOrcamento;
    private javax.swing.JPanel pLoginIncorretoMenuLogin;
    private javax.swing.JPanel pMenuAddAnimal;
    private javax.swing.JPanel pMenuAddCliente;
    private javax.swing.JPanel pMenuAnimal;
    private javax.swing.JPanel pMenuCliente;
    private javax.swing.JPanel pMenuFuncionario;
    private javax.swing.JPanel pMenuLogin;
    private javax.swing.JPanel pMenuPrincipal;
    private javax.swing.JPanel pMenuServico;
    private javax.swing.JRadioButton rbFemeaAddAnimal;
    private javax.swing.JRadioButton rbMachoAddAnimal;
    private javax.swing.JTextField txtBairroAddCliente;
    private javax.swing.JTextField txtComplementoAddCliente;
    private javax.swing.JFormattedTextField txtCpfAddCliente;
    private javax.swing.JFormattedTextField txtDataNascAddCliente;
    private javax.swing.JTextField txtEnderecoAddCliente;
    private javax.swing.JTextField txtLoginMenuLogin;
    private javax.swing.JTextField txtNomeAddAnimal;
    private javax.swing.JTextField txtNomeAddCliente;
    private javax.swing.JTextField txtRacaAddAnimal;
    private javax.swing.JPasswordField txtSenhaMenuLogin;
    private javax.swing.JFormattedTextField txtTelefone1AddCliente;
    private javax.swing.JFormattedTextField txtTelefone2AddCliente;
    // End of variables declaration//GEN-END:variables
    private Campovazio cp = new Campovazio();

    private void fechar() {
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja sair do programa?", "ATENÇÃO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();

        }
    }

}
