/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

/**
 *
 * @author matheus
 */
public class TelaBuscar extends javax.swing.JPanel {

    /**
     * Creates new form Buscar
     */
    public TelaBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloBuscar = new javax.swing.JLabel();
        lbBuscarPorNome = new javax.swing.JLabel();
        lbBuscarPorCpf = new javax.swing.JLabel();
        txtBuscarPorNome = new javax.swing.JTextField();
        txtBuscarPorCpf = new javax.swing.JTextField();
        bBuscarPorNome = new javax.swing.JButton();
        bBuscarPorCpf = new javax.swing.JButton();

        lbTituloBuscar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTituloBuscar.setText("BUSCAR #######");

        lbBuscarPorNome.setText("BUSCAR POR NOME:");

        lbBuscarPorCpf.setText("BUSCAR POR CPF:");

        bBuscarPorNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N

        bBuscarPorCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBuscarPorCpf)
                            .addComponent(lbBuscarPorNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscarPorNome, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtBuscarPorCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBuscarPorNome)
                            .addComponent(bBuscarPorCpf)))
                    .addComponent(lbTituloBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTituloBuscar)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarPorNome)
                    .addComponent(txtBuscarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarPorNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarPorCpf)
                    .addComponent(txtBuscarPorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarPorCpf))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarPorCpf;
    private javax.swing.JButton bBuscarPorNome;
    private javax.swing.JLabel lbBuscarPorCpf;
    private javax.swing.JLabel lbBuscarPorNome;
    private javax.swing.JLabel lbTituloBuscar;
    private javax.swing.JTextField txtBuscarPorCpf;
    private javax.swing.JTextField txtBuscarPorNome;
    // End of variables declaration//GEN-END:variables
}
