/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

import br.edu.uesb.petshop.model.PetShop;
import br.edu.uesb.petshop.enumerado.EnumView;

/**
 *
 * @author matheus
 */
public class TelaMenuServico extends javax.swing.JPanel {

    /**
     * Creates new form TelaMenuServico
     */
    public TelaMenuServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloMenuServico = new javax.swing.JLabel();
        bVoltarMenuServico = new javax.swing.JButton();
        bBuscarServico = new javax.swing.JButton();
        bNovoServico = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        lbTituloMenuServico.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuServico.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuServico.setText("ATENDIMENTO");

        bVoltarMenuServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/15.png"))); // NOI18N
        bVoltarMenuServico.setText("VOLTAR");
        bVoltarMenuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuServicoActionPerformed(evt);
            }
        });

        bBuscarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N
        bBuscarServico.setText("BUSCAR ATENDIMENTO");
        bBuscarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bBuscarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarServicoActionPerformed(evt);
            }
        });

        bNovoServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.png"))); // NOI18N
        bNovoServico.setText("NOVO ATENDIMENTO");
        bNovoServico.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoServico.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoServico.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bVoltarMenuServico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bNovoServico, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(bBuscarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbTituloMenuServico))
                        .addGap(132, 132, 132))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTituloMenuServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNovoServico, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(bBuscarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(bVoltarMenuServico)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarMenuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuServicoActionPerformed

        PetShop.tela.showView(EnumView.TELAPRINCIPAL);
        
    }//GEN-LAST:event_bVoltarMenuServicoActionPerformed

    private void bNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoServicoActionPerformed

        PetShop.tela.showView(EnumView.TELAADDATENDIMENTO);
        
    }//GEN-LAST:event_bNovoServicoActionPerformed

    private void bBuscarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarServicoActionPerformed
      
        PetShop.tela.showView(EnumView.TELABUSCARATENDIMENTO);
        
    }//GEN-LAST:event_bBuscarServicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarServico;
    private javax.swing.JButton bNovoServico;
    private javax.swing.JButton bVoltarMenuServico;
    private javax.swing.JLabel lbTituloMenuServico;
    // End of variables declaration//GEN-END:variables
}
