/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

/**
 *
 * @author matheus
 */
public class TelaBuscarFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form Buscar
     */
    public TelaBuscarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloBuscarFuncionario = new javax.swing.JLabel();
        lbBuscarPorNomeFuncionario = new javax.swing.JLabel();
        lbBuscarPorCpfFuncionario = new javax.swing.JLabel();
        txtBuscarPorNomeFuncionario = new javax.swing.JTextField();
        txtBuscarPorCpfFuncionario = new javax.swing.JTextField();
        bBuscarPorNomeFuncionario = new javax.swing.JButton();
        bBuscarPorCpfFuncionario = new javax.swing.JButton();

        lbTituloBuscarFuncionario.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTituloBuscarFuncionario.setText("BUSCAR FUNCIONÁRIO");

        lbBuscarPorNomeFuncionario.setText("BUSCAR POR NOME:");

        lbBuscarPorCpfFuncionario.setText("BUSCAR POR CPF:");

        bBuscarPorNomeFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N

        bBuscarPorCpfFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscarPorCpfFuncionario)
                    .addComponent(lbBuscarPorNomeFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscarPorNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtBuscarPorCpfFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBuscarPorNomeFuncionario)
                    .addComponent(bBuscarPorCpfFuncionario))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbTituloBuscarFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbTituloBuscarFuncionario)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarPorNomeFuncionario)
                    .addComponent(txtBuscarPorNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarPorNomeFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarPorCpfFuncionario)
                    .addComponent(txtBuscarPorCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarPorCpfFuncionario))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarPorCpfFuncionario;
    private javax.swing.JButton bBuscarPorNomeFuncionario;
    private javax.swing.JLabel lbBuscarPorCpfFuncionario;
    private javax.swing.JLabel lbBuscarPorNomeFuncionario;
    private javax.swing.JLabel lbTituloBuscarFuncionario;
    private javax.swing.JTextField txtBuscarPorCpfFuncionario;
    private javax.swing.JTextField txtBuscarPorNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
