/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

/**
 *
 * @author matheus
 */
public class TelaMenuAnimal extends javax.swing.JPanel {

    /**
     * Creates new form TelaMenuAnimal
     */
    public TelaMenuAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloMenuAnimal = new javax.swing.JLabel();
        bVoltarMenuAnimal = new javax.swing.JButton();
        bBuscarAnimal = new javax.swing.JButton();
        bNovoAnimal = new javax.swing.JButton();

        lbTituloMenuAnimal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuAnimal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuAnimal.setText("ANIMAL");

        bVoltarMenuAnimal.setText("VOLTAR");
        bVoltarMenuAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuAnimalActionPerformed(evt);
            }
        });

        bBuscarAnimal.setText("BUSCAR ANIMAL");

        bNovoAnimal.setText("NOVO ANIMAL");
        bNovoAnimal.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTituloMenuAnimal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bNovoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bVoltarMenuAnimal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenuAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNovoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(bBuscarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(bVoltarMenuAnimal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarMenuAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuAnimalActionPerformed
//        pMenuPrincipal.setVisible(true);
//        pMenuAnimal.setVisible(false);
    }//GEN-LAST:event_bVoltarMenuAnimalActionPerformed

    private void bNovoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoAnimalActionPerformed
//        pMenuAddAnimal.setVisible(true);
//        pMenuAnimal.setVisible(false);
    }//GEN-LAST:event_bNovoAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarAnimal;
    private javax.swing.JButton bNovoAnimal;
    private javax.swing.JButton bVoltarMenuAnimal;
    private javax.swing.JLabel lbTituloMenuAnimal;
    // End of variables declaration//GEN-END:variables
}
