/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

/**
 *
 * @author matheus
 */
public class TelaBuscarAnimal extends javax.swing.JPanel {

    /**
     * Creates new form Buscar
     */
    public TelaBuscarAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloBuscarAnimal = new javax.swing.JLabel();
        lbBuscarPorNomeAnimal = new javax.swing.JLabel();
        lbBuscarDono = new javax.swing.JLabel();
        txtBuscarPorNomeAnimal = new javax.swing.JTextField();
        txtBuscarDono = new javax.swing.JTextField();
        bBuscarPorNomeAnimal = new javax.swing.JButton();
        bBuscarPorDono = new javax.swing.JButton();

        lbTituloBuscarAnimal.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTituloBuscarAnimal.setText("BUSCAR ANIMAL");

        lbBuscarPorNomeAnimal.setText("BUSCAR POR NOME:");

        lbBuscarDono.setText("BUSCAR PELO DONO:");

        bBuscarPorNomeAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N

        bBuscarPorDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbTituloBuscarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBuscarDono)
                            .addComponent(lbBuscarPorNomeAnimal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscarPorNomeAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtBuscarDono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBuscarPorNomeAnimal)
                            .addComponent(bBuscarPorDono))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTituloBuscarAnimal)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarPorNomeAnimal)
                    .addComponent(txtBuscarPorNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarPorNomeAnimal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarDono)
                    .addComponent(txtBuscarDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarPorDono))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarPorDono;
    private javax.swing.JButton bBuscarPorNomeAnimal;
    private javax.swing.JLabel lbBuscarDono;
    private javax.swing.JLabel lbBuscarPorNomeAnimal;
    private javax.swing.JLabel lbTituloBuscarAnimal;
    private javax.swing.JTextField txtBuscarDono;
    private javax.swing.JTextField txtBuscarPorNomeAnimal;
    // End of variables declaration//GEN-END:variables
}
