/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.uesb.petshop.gui;

/**
 *
 * @author Laherce Gomes
 */
public class TelaAddCirurgia extends javax.swing.JPanel {

    /**
     * Creates new form TelaAddCirurgia
     */
    public TelaAddCirurgia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelarCirurgias = new javax.swing.JButton();
        jCheckBoxCirurgia1 = new javax.swing.JCheckBox();
        jLabelCirurgias = new javax.swing.JLabel();
        jCheckBoxCirurgia2 = new javax.swing.JCheckBox();
        jButtonAddCirurgias = new javax.swing.JButton();
        jCheckBoxCirurgia4 = new javax.swing.JCheckBox();
        jCheckBoxCirurgia5 = new javax.swing.JCheckBox();
        jCheckBoxCirurgia3 = new javax.swing.JCheckBox();

        jButtonCancelarCirurgias.setText("CANCELAR");

        jCheckBoxCirurgia1.setText("Cirurgia 01");
        jCheckBoxCirurgia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCirurgia1ActionPerformed(evt);
            }
        });

        jLabelCirurgias.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelCirurgias.setText("CIRURGIAS");

        jCheckBoxCirurgia2.setText("Cirurgia 02");

        jButtonAddCirurgias.setText("ADICIONAR");

        jCheckBoxCirurgia4.setText("Cirurgia 04");

        jCheckBoxCirurgia5.setText("Cirurgia 05");

        jCheckBoxCirurgia3.setText("Cirurgia 03");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCirurgia5)
                    .addComponent(jCheckBoxCirurgia2)
                    .addComponent(jCheckBoxCirurgia1)
                    .addComponent(jCheckBoxCirurgia3)
                    .addComponent(jCheckBoxCirurgia4))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelarCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCirurgias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelarCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxCirurgia1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCirurgia2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCirurgia3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCirurgia4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCirurgia5)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCirurgia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCirurgia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCirurgia1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCirurgias;
    private javax.swing.JButton jButtonCancelarCirurgias;
    private javax.swing.JCheckBox jCheckBoxCirurgia1;
    private javax.swing.JCheckBox jCheckBoxCirurgia2;
    private javax.swing.JCheckBox jCheckBoxCirurgia3;
    private javax.swing.JCheckBox jCheckBoxCirurgia4;
    private javax.swing.JCheckBox jCheckBoxCirurgia5;
    private javax.swing.JLabel jLabelCirurgias;
    // End of variables declaration//GEN-END:variables
}
