/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

import br.edu.uesb.petshop.enumerado.EnumView;
import br.edu.uesb.petshop.model.PetShop;

/**
 *
 * @author matheus
 */
public class TelaMenuAnimal extends javax.swing.JPanel {

    /**
     * Creates new form TelaMenuAnimal
     */
    public TelaMenuAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloMenuAnimal = new javax.swing.JLabel();
        bVoltarMenuAnimal = new javax.swing.JButton();
        bBuscarAnimal = new javax.swing.JButton();
        bNovoAnimal = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        lbTituloMenuAnimal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloMenuAnimal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloMenuAnimal.setText("ANIMAL");

        bVoltarMenuAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/15.png"))); // NOI18N
        bVoltarMenuAnimal.setText("VOLTAR");
        bVoltarMenuAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarMenuAnimalActionPerformed(evt);
            }
        });

        bBuscarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/7.png"))); // NOI18N
        bBuscarAnimal.setText("BUSCAR ANIMAL");
        bBuscarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarAnimalActionPerformed(evt);
            }
        });

        bNovoAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/77.png"))); // NOI18N
        bNovoAnimal.setText("NOVO ANIMAL");
        bNovoAnimal.setMaximumSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.setMinimumSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.setPreferredSize(new java.awt.Dimension(122, 26));
        bNovoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bNovoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(bBuscarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addComponent(lbTituloMenuAnimal))
                    .addComponent(bVoltarMenuAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTituloMenuAnimal)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBuscarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNovoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addComponent(bVoltarMenuAnimal)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarMenuAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarMenuAnimalActionPerformed

        PetShop.tela.showView(EnumView.TELAPRINCIPAL);
        
    }//GEN-LAST:event_bVoltarMenuAnimalActionPerformed

    private void bNovoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoAnimalActionPerformed

        
        PetShop.tela.showView(EnumView.TELAADDANIMAL);
    }//GEN-LAST:event_bNovoAnimalActionPerformed

    private void bBuscarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarAnimalActionPerformed

        PetShop.tela.showView(EnumView.TELABUSCARANIMAL);
        
    }//GEN-LAST:event_bBuscarAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarAnimal;
    private javax.swing.JButton bNovoAnimal;
    private javax.swing.JButton bVoltarMenuAnimal;
    private javax.swing.JLabel lbTituloMenuAnimal;
    // End of variables declaration//GEN-END:variables
}
