/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.uesb.petshop.gui;

/**
 *
 * @author Laherce Gomes
 */
public class TelaAddServico extends javax.swing.JPanel {

    /**
     * Creates new form TelaAddServiço
     */
    public TelaAddServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox6 = new javax.swing.JCheckBox();
        jLabelServicos = new javax.swing.JLabel();
        jButtonAddServiços = new javax.swing.JButton();
        jButtonCancelarServiços = new javax.swing.JButton();
        jCheckBoxServiço1 = new javax.swing.JCheckBox();
        jCheckBoxServiço2 = new javax.swing.JCheckBox();
        jCheckBoxServiço3 = new javax.swing.JCheckBox();
        jCheckBoxServiço4 = new javax.swing.JCheckBox();
        jCheckBoxServiço5 = new javax.swing.JCheckBox();

        jCheckBox6.setText("jCheckBox6");

        jLabelServicos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelServicos.setText("SERVIÇOS");

        jButtonAddServiços.setText("ADICIONAR");

        jButtonCancelarServiços.setText("CANCELAR");

        jCheckBoxServiço1.setText("Banho Comum");
        jCheckBoxServiço1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxServiço1ActionPerformed(evt);
            }
        });

        jCheckBoxServiço2.setText("Banho Terapeutico");

        jCheckBoxServiço3.setText("Tosa Higienica");

        jCheckBoxServiço4.setText("Hotelzinha");

        jCheckBoxServiço5.setText("Aplicação de Medicamentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxServiço5)
                            .addComponent(jCheckBoxServiço2)
                            .addComponent(jCheckBoxServiço1)
                            .addComponent(jCheckBoxServiço3)
                            .addComponent(jCheckBoxServiço4))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCancelarServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelServicos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelarServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxServiço1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxServiço2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxServiço3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxServiço4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxServiço5)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxServiço1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxServiço1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxServiço1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddServiços;
    private javax.swing.JButton jButtonCancelarServiços;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBoxServiço1;
    private javax.swing.JCheckBox jCheckBoxServiço2;
    private javax.swing.JCheckBox jCheckBoxServiço3;
    private javax.swing.JCheckBox jCheckBoxServiço4;
    private javax.swing.JCheckBox jCheckBoxServiço5;
    private javax.swing.JLabel jLabelServicos;
    // End of variables declaration//GEN-END:variables
}
