/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uesb.petshop.gui;

/**
 *
 * @author matheus
 */
public class TelaAddCliente extends javax.swing.JPanel {

    /**
     * Creates new form TelaAddCliente
     */
    public TelaAddCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloAddCliente = new javax.swing.JLabel();
        txtNomeAddCliente = new javax.swing.JTextField();
        lbNomeAddCdiente = new javax.swing.JLabel();
        txtEnderecoAddCliente = new javax.swing.JTextField();
        lbEnderecoAddCliente = new javax.swing.JLabel();
        lbBairroAddCliente = new javax.swing.JLabel();
        txtBairroAddCliente = new javax.swing.JTextField();
        lbComplementoAddCliente = new javax.swing.JLabel();
        txtComplementoAddCliente = new javax.swing.JTextField();
        lbSexoAddCliente = new javax.swing.JLabel();
        cbSexoAddCliente = new javax.swing.JComboBox();
        lbcpfAddCliente = new javax.swing.JLabel();
        txtCpfAddCliente = new javax.swing.JFormattedTextField();
        lbDataNascAddCliente = new javax.swing.JLabel();
        txtDataNascAddCliente = new javax.swing.JFormattedTextField();
        lbTelefone1AddCliente = new javax.swing.JLabel();
        txtTelefone1AddCliente = new javax.swing.JFormattedTextField();
        lbTelefone2AddCliente = new javax.swing.JLabel();
        txtTelefone2AddCliente = new javax.swing.JFormattedTextField();
        bLimparAddCliente = new javax.swing.JButton();
        bSalvarCadastroAddCliente = new javax.swing.JButton();
        bVoltarAddCliente = new javax.swing.JButton();
        lbFaltaMensagemAddCliente = new javax.swing.JLabel();

        lbTituloAddCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTituloAddCliente.setText("ADICIONAR CLIENTE");

        lbNomeAddCdiente.setText("Nome:");

        lbEnderecoAddCliente.setText("Endereço:");

        lbBairroAddCliente.setText("Bairro:");

        lbComplementoAddCliente.setText("Complemento:");

        lbSexoAddCliente.setText("Sexo:");

        cbSexoAddCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbSexoAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoAddClienteActionPerformed(evt);
            }
        });

        lbcpfAddCliente.setText("CPF:");

        try {
            txtCpfAddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbDataNascAddCliente.setText("Data Nasc.:");

        try {
            txtDataNascAddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone1AddCliente.setText("Telefone 1:");

        try {
            txtTelefone1AddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone2AddCliente.setText("Telefone 2:");

        try {
            txtTelefone2AddCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bLimparAddCliente.setText("LIMPAR");
        bLimparAddCliente.setPreferredSize(new java.awt.Dimension(67, 27));
        bLimparAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparAddClienteActionPerformed(evt);
            }
        });

        bSalvarCadastroAddCliente.setText("SALVAR CADASTRO");
        bSalvarCadastroAddCliente.setPreferredSize(new java.awt.Dimension(4075, 27));
        bSalvarCadastroAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarCadastroAddClienteActionPerformed(evt);
            }
        });

        bVoltarAddCliente.setText("VOLTAR");
        bVoltarAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarAddClienteActionPerformed(evt);
            }
        });

        lbFaltaMensagemAddCliente.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaMensagemAddCliente.setText("Por favor preencha os campos restantes *");
        lbFaltaMensagemAddCliente.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lbTituloAddCliente)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbComplementoAddCliente)
                                .addGap(18, 18, 18)
                                .addComponent(txtComplementoAddCliente))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEnderecoAddCliente)
                                    .addComponent(lbNomeAddCdiente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNomeAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEnderecoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbBairroAddCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBairroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbSexoAddCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSexoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbcpfAddCliente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbTelefone2AddCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefone2AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtCpfAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbDataNascAddCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataNascAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(bLimparAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bVoltarAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(bSalvarCadastroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTelefone1AddCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone1AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lbFaltaMensagemAddCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloAddCliente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeAddCdiente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnderecoAddCliente)
                    .addComponent(lbBairroAddCliente)
                    .addComponent(txtBairroAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplementoAddCliente)
                    .addComponent(txtComplementoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcpfAddCliente)
                    .addComponent(txtCpfAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataNascAddCliente)
                    .addComponent(txtDataNascAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexoAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexoAddCliente))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbTelefone1AddCliente)
                                .addComponent(txtTelefone1AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTelefone2AddCliente)
                                .addComponent(txtTelefone2AddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(bSalvarCadastroAddCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLimparAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVoltarAddCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbFaltaMensagemAddCliente)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbSexoAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoAddClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoAddClienteActionPerformed

    private void bLimparAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparAddClienteActionPerformed
        txtNomeAddCliente.setText("");
        txtEnderecoAddCliente.setText("");
        txtComplementoAddCliente.setText("");
        txtBairroAddCliente.setText("");
        txtCpfAddCliente.setText("");
        txtDataNascAddCliente.setText("");
        txtTelefone1AddCliente.setText("");
        txtTelefone2AddCliente.setText("");
        cbSexoAddCliente.setSelectedItem(0);
    }//GEN-LAST:event_bLimparAddClienteActionPerformed

    private void bSalvarCadastroAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarCadastroAddClienteActionPerformed

//        cp.textfield(txtNomeAddCliente);
//        cp.textfield(txtEnderecoAddCliente);
//        cp.textfield(txtBairroAddCliente);
//        cp.formattedtextfield(txtCpfAddCliente);
//        cp.formattedtextfield(txtDataNascAddCliente);
//        cp.formattedtextfield(txtTelefone1AddCliente);
//        cp.combobox(cbSexoAddCliente);

        //        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();
        //
        //        //se todos os campos estiverem preenchidos ele add ao banco de dados
        //        if ((cp.textfield(txtNomeAddCliente) == false) && (cp.textfield(txtEnderecoAddCliente) == false)
            //            && (cp.textfield(txtBairroAddCliente) == false)
            //            && (cp.formattedtextfield(txtCpfAddCliente) == false) && (cp.formattedtextfield(txtDataNascAddCliente) == false)
            //            && (cp.formattedtextfield(txtTelefone1AddCliente) == false) && (cp.combobox(cbSexoAddCliente) == false)) {
            //
            //            //add
            //            try {
                //                query.executeUpdate("INSERT INTO \"Cliente\"(\n"
                    //                    + "            nome, endereco, bairro, complemento, sexo, cpf, datanascimento, telefone1, \n"
                    //                    + "            telefone2)\n"
                    //                    + "    VALUES ('" + txtNomeAddCliente.getText() + "','" + txtEnderecoAddCliente.getText() + "','" + txtBairroAddCliente.getText()
                    //                    + "','" + txtComplementoAddCliente.getText() + "','" + cbSexoAddCliente.getSelectedItem() + "','" + txtCpfAddCliente.getText()
                    //                    + "', '" + txtDataNascAddCliente.getText() + "', '" + txtTelefone1AddCliente.getText() + "','" + txtTelefone2AddCliente.getText() + "');");
                //
                //                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", null, JOptionPane.PLAIN_MESSAGE, null);
                //                bLimparAddClienteActionPerformed(evt);//limparcampos
                //
                //            } catch (Exception e) {
                //                System.out.println(e);
                //                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados ", "ERRO", JOptionPane.ERROR_MESSAGE, null);
                //            }
            //
            //            lbFaltaMensagemAddCliente.setVisible(false);
            //        } else {
            //            lbFaltaMensagemAddCliente.setVisible(true);
            //        }
    }//GEN-LAST:event_bSalvarCadastroAddClienteActionPerformed

    private void bVoltarAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarAddClienteActionPerformed
//        TelaMenuAddCliente.setVisible(false);
//        pMenuCliente.setVisible(true);
//        bLimparAddClienteActionPerformed(evt);
    }//GEN-LAST:event_bVoltarAddClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLimparAddCliente;
    private javax.swing.JButton bSalvarCadastroAddCliente;
    private javax.swing.JButton bVoltarAddCliente;
    private javax.swing.JComboBox cbSexoAddCliente;
    private javax.swing.JLabel lbBairroAddCliente;
    private javax.swing.JLabel lbComplementoAddCliente;
    private javax.swing.JLabel lbDataNascAddCliente;
    private javax.swing.JLabel lbEnderecoAddCliente;
    private javax.swing.JLabel lbFaltaMensagemAddCliente;
    private javax.swing.JLabel lbNomeAddCdiente;
    private javax.swing.JLabel lbSexoAddCliente;
    private javax.swing.JLabel lbTelefone1AddCliente;
    private javax.swing.JLabel lbTelefone2AddCliente;
    private javax.swing.JLabel lbTituloAddCliente;
    private javax.swing.JLabel lbcpfAddCliente;
    private javax.swing.JTextField txtBairroAddCliente;
    private javax.swing.JTextField txtComplementoAddCliente;
    private javax.swing.JFormattedTextField txtCpfAddCliente;
    private javax.swing.JFormattedTextField txtDataNascAddCliente;
    private javax.swing.JTextField txtEnderecoAddCliente;
    private javax.swing.JTextField txtNomeAddCliente;
    private javax.swing.JFormattedTextField txtTelefone1AddCliente;
    private javax.swing.JFormattedTextField txtTelefone2AddCliente;
    // End of variables declaration//GEN-END:variables
}
